import 'package:flutter/material.dart';

/// Mapa compartido de nombre-de-ícono → IconData para glosas LSB.
/// Centralizado para evitar duplicación entre SemanticNode y CardGrid.
const Map<String, IconData> kLsbIconMap = {
  'person': Icons.person, 'child_care': Icons.child_care,
  'woman': Icons.woman, 'man': Icons.man, 'people': Icons.people,
  'family_restroom': Icons.family_restroom,
  'front_hand': Icons.front_hand,
  'record_voice_over': Icons.record_voice_over,
  'assignment': Icons.assignment, 'send': Icons.send, 'help': Icons.help,
  'payments': Icons.payments, 'autorenew': Icons.autorenew,
  'app_registration': Icons.app_registration,
  'how_to_reg': Icons.how_to_reg,
  'download': Icons.download, 'upload': Icons.upload, 'draw': Icons.draw,
  'article': Icons.article,
  'workspace_premium': Icons.workspace_premium,
  'description': Icons.description, 'badge': Icons.badge,
  'child_friendly': Icons.child_friendly, 'favorite': Icons.favorite,
  'sentiment_very_dissatisfied': Icons.sentiment_very_dissatisfied,
  'directions_car': Icons.directions_car,
  'receipt_long': Icons.receipt_long,
  'content_copy': Icons.content_copy, 'flight': Icons.flight,
  'verified_user': Icons.verified_user,
  'question_answer': Icons.question_answer, 'feedback': Icons.feedback,
  'event': Icons.event,
  'confirmation_number': Icons.confirmation_number,
  'today': Icons.today, 'access_time': Icons.access_time,
  'history': Icons.history, 'wb_sunny': Icons.wb_sunny,
  'wb_twilight': Icons.wb_twilight, 'date_range': Icons.date_range,
  'account_balance': Icons.account_balance, 'domain': Icons.domain,
  'menu_book': Icons.menu_book, 'request_quote': Icons.request_quote,
  'account_balance_wallet': Icons.account_balance_wallet,
  'local_hospital': Icons.local_hospital, 'school': Icons.school,
  'gavel': Icons.gavel, 'local_police': Icons.local_police,
  'shield': Icons.shield, 'business': Icons.business,
  'sign_language': Icons.sign_language, 'info': Icons.info,
  'medical_services': Icons.medical_services, 'balance': Icons.balance,
  'support_agent': Icons.support_agent, 'explore': Icons.explore,
  'emergency': Icons.emergency,
  'priority_high': Icons.priority_high, 'sos': Icons.sos,
  'crisis_alert': Icons.crisis_alert, 'sick': Icons.sick,
  'healing': Icons.healing, 'help_outline': Icons.help_outline,
  'location_off': Icons.location_off,
  'credit_card': Icons.credit_card,
  'search': Icons.search, 'report': Icons.report,
  'warning': Icons.warning, 'sports_mma': Icons.sports_mma,
  'back_hand': Icons.back_hand, 'waving_hand': Icons.waving_hand,
  'directions_run': Icons.directions_run, 'groups': Icons.groups,
  'nature_people': Icons.nature_people, 'person_off': Icons.person_off,
};
