import 'package:flutter/material.dart';

/// Mapa compartido de nombre-de-ícono → IconData para glosas LSB.
/// Centralizado para evitar duplicación entre SemanticNode y CardGrid.
const Map<String, IconData> kLsbIconMap = {
  'person': Icons.person, 'child_care': Icons.child_care,
  'woman': Icons.woman, 'man': Icons.man, 'people': Icons.people,
  'family_restroom': Icons.family_restroom,
  'front_hand': Icons.front_hand,
  'record_voice_over': Icons.record_voice_over,
  'assignment': Icons.assignment, 'send': Icons.send, 'help': Icons.help,
  'payments': Icons.payments, 'autorenew': Icons.autorenew,
  'inventory_2': Icons.inventory_2,
  'app_registration': Icons.app_registration,
  'how_to_reg': Icons.how_to_reg,
  'download': Icons.download, 'upload': Icons.upload, 'draw': Icons.draw,
  'article': Icons.article,
  'workspace_premium': Icons.workspace_premium,
  'description': Icons.description, 'badge': Icons.badge,
  'child_friendly': Icons.child_friendly, 'favorite': Icons.favorite,
  'sentiment_very_dissatisfied': Icons.sentiment_very_dissatisfied,
  'directions_car': Icons.directions_car,
  'receipt_long': Icons.receipt_long,
  'content_copy': Icons.content_copy, 'flight': Icons.flight,
  'verified_user': Icons.verified_user,
  'question_answer': Icons.question_answer, 'feedback': Icons.feedback,
  'event': Icons.event,
  'confirmation_number': Icons.confirmation_number,
  'today': Icons.today, 'access_time': Icons.access_time,
  'history': Icons.history, 'wb_sunny': Icons.wb_sunny,
  'wb_twilight': Icons.wb_twilight, 'date_range': Icons.date_range,
  'account_balance': Icons.account_balance, 'domain': Icons.domain,
  'menu_book': Icons.menu_book, 'request_quote': Icons.request_quote,
  'account_balance_wallet': Icons.account_balance_wallet,
  'local_hospital': Icons.local_hospital, 'school': Icons.school,
  'gavel': Icons.gavel, 'local_police': Icons.local_police,
  'shield': Icons.shield, 'business': Icons.business,
  'sign_language': Icons.sign_language, 'info': Icons.info,
  'medical_services': Icons.medical_services, 'balance': Icons.balance,
  'support_agent': Icons.support_agent, 'explore': Icons.explore,
  'emergency': Icons.emergency,
  'priority_high': Icons.priority_high, 'sos': Icons.sos,
  'crisis_alert': Icons.crisis_alert, 'sick': Icons.sick,
  'healing': Icons.healing, 'help_outline': Icons.help_outline,
  'location_off': Icons.location_off,
  'credit_card': Icons.credit_card,
  'search': Icons.search, 'report': Icons.report,
  'warning': Icons.warning, 'sports_mma': Icons.sports_mma,
  'back_hand': Icons.back_hand, 'waving_hand': Icons.waving_hand,
  'directions_run': Icons.directions_run, 'groups': Icons.groups,
  'nature_people': Icons.nature_people, 'person_off': Icons.person_off,
  'search_off': Icons.search_off, 'directions_walk': Icons.directions_walk,
  'work': Icons.work, 'home': Icons.home, 'add_road': Icons.add_road,
  'storefront': Icons.storefront, 'departure_board': Icons.departure_board,
  'forest': Icons.forest, 'park': Icons.park, 'atm': Icons.atm,
  'directions_bus': Icons.directions_bus, 'local_taxi': Icons.local_taxi,
  'two_wheeler': Icons.two_wheeler, 'pedal_bike': Icons.pedal_bike,
  'smartphone': Icons.smartphone, 'laptop': Icons.laptop,
  'attach_money': Icons.attach_money, 'vpn_key': Icons.vpn_key,
  'watch': Icons.watch, 'backpack': Icons.backpack,
  'shopping_bag': Icons.shopping_bag, 'headphones': Icons.headphones,
  'diamond': Icons.diamond, 'auto_awesome': Icons.auto_awesome,
  'link': Icons.link, 'visibility': Icons.visibility, 'sunny': Icons.sunny,
  'checkroom': Icons.checkroom, 'dry_cleaning': Icons.dry_cleaning,
  'straighten': Icons.straighten, 'sports_baseball': Icons.sports_baseball,
  'sports_motorsports': Icons.sports_motorsports,
  'face_retouching_off': Icons.face_retouching_off,
  'height': Icons.height, 'compress': Icons.compress,
  'fitness_center': Icons.fitness_center, 'elderly': Icons.elderly,
  'person_pin': Icons.person_pin, 'face': Icons.face, 'face_2': Icons.face_2,
  'face_4': Icons.face_4, 'face_6': Icons.face_6, 'cut': Icons.cut,
  'waves': Icons.waves,
  'radio_button_unchecked': Icons.radio_button_unchecked,
  'brush': Icons.brush, 'circle': Icons.circle,
  'panorama_fish_eye': Icons.panorama_fish_eye,
  'water_drop': Icons.water_drop, 'cloud': Icons.cloud,
  'brightness_5': Icons.brightness_5, 'brightness_3': Icons.brightness_3,
  'hardware': Icons.hardware, 'gpp_bad': Icons.gpp_bad,
  'mood_bad': Icons.mood_bad,
  'sentiment_dissatisfied': Icons.sentiment_dissatisfied,
  'nights_stay': Icons.nights_stay,
};
