"""Glosa → rol gramatical y forma en español, para componer la oración base.

Lo genera `tool/sync_vocabulary.dart` desde el léxico del cliente
(`lib/core/domain/services/local_sentence_assembler_lexicon.dart`): servidor
y cliente componen la misma oración a partir de las mismas glosas. No se
edita a mano. Lo usa `lambda_function.py`.
"""

GLOSS_LEXICON = {
    # GENERADO por tool/sync_vocabulary.dart — no editar a mano.
    # Fuente: el lexicón del cliente, para que servidor y cliente
    # compongan la misma oración a partir de las mismas glosas.
    "0": {"rol": "VERBO", "es": "0"},
    "1": {"rol": "VERBO", "es": "1"},
    "2": {"rol": "VERBO", "es": "2"},
    "3": {"rol": "VERBO", "es": "3"},
    "4": {"rol": "VERBO", "es": "4"},
    "5": {"rol": "VERBO", "es": "5"},
    "6": {"rol": "VERBO", "es": "6"},
    "7": {"rol": "VERBO", "es": "7"},
    "8": {"rol": "VERBO", "es": "8"},
    "9": {"rol": "VERBO", "es": "9"},
    "A": {"rol": "VERBO", "es": "a"},
    "ABOGADO": {"rol": "SERVICIO", "es": "un abogado"},
    "ABRIR": {"rol": "VERBO", "es": "abrí"},
    "ABUSAR": {"rol": "VERBO", "es": "cometió abusos", "agresor": "cometió abusos"},
    "ACEPTAR": {"rol": "VERBO", "es": "acepto"},
    "ACOMPAÑAR": {"rol": "VERBO", "es": "acompañar"},
    "ADULTO": {"rol": "DESCRIPTOR", "es": "adulto", "persona": True},
    "AHORA": {"rol": "TIEMPO", "es": "ahora mismo"},
    "ALCALDIA": {"rol": "INSTITUCION", "es": "en la alcaldía"},
    "ALLA": {"rol": "LUGAR", "es": "allá"},
    "ALLI": {"rol": "LUGAR", "es": "allí"},
    "ALTO": {"rol": "DESCRIPTOR", "es": "alto"},
    "AL_LADO": {"rol": "LUGAR", "es": "al lado"},
    "AMBOS": {"rol": "SUJETO", "es": "ambos"},
    "AMENAZAR": {"rol": "VERBO", "es": "amenazó", "agresor": "amenazó"},
    "AMIGO": {"rol": "DESCRIPTOR", "es": "un amigo", "persona": True},
    "ANDAR": {"rol": "VERBO", "es": "caminaba"},
    "ANOS_EDAD": {"rol": "DESCONOCIDO", "es": "tengo esa edad"},
    "ANTEAYER": {"rol": "TIEMPO", "es": "anteayer"},
    "APELLIDO": {"rol": "DESCONOCIDO", "es": "mi apellido es"},
    "AQUI": {"rol": "LUGAR", "es": "aquí"},
    "ARREGLAR": {"rol": "VERBO", "es": "quiero corregir"},
    "ARRESTAR": {"rol": "VERBO", "es": "arrestaron"},
    "ASISTENCIA": {"rol": "DOCUMENTO", "es": "asistencia"},
    "ASISTENTE": {"rol": "SERVICIO", "es": "un asistente"},
    "ASOCIACION_SORDOS": {"rol": "DESCRIPTOR", "es": "la asociación de sordos", "persona": True},
    "ATENDER": {"rol": "VERBO", "es": "atender"},
    "ATRAS": {"rol": "LUGAR", "es": "atrás"},
    "AUDIENCIA": {"rol": "TRAMITE", "es": "una audiencia"},
    "AUMENTAR": {"rol": "VERBO", "es": "quiero agregar información"},
    "AUN": {"rol": "TIEMPO", "es": "aún"},
    "AUTO": {"rol": "OBJETO", "es": "mi auto"},
    "AUTORIDAD": {"rol": "INSTITUCION", "es": "la autoridad"},
    "AUXILIO": {"rol": "URGENCIA", "es": "auxilio urgente"},
    "AVENIDA": {"rol": "LUGAR", "es": "en la avenida"},
    "AVISAR": {"rol": "VERBO", "es": "avisar"},
    "AYER": {"rol": "TIEMPO", "es": "ayer"},
    "AYUDAR": {"rol": "VERBO", "es": "necesito ayuda"},
    "AZUL": {"rol": "DESCRIPTOR", "es": "de color azul"},
    "AÑO": {"rol": "TIEMPO", "es": "año"},
    "AÑO_PASADO": {"rol": "TIEMPO", "es": "el año pasado"},
    "B": {"rol": "VERBO", "es": "b"},
    "BAJO": {"rol": "DESCRIPTOR", "es": "bajo"},
    "BANCO": {"rol": "LUGAR", "es": "en el banco"},
    "BARRIO": {"rol": "LUGAR", "es": "en el barrio"},
    "BICICLETA": {"rol": "OBJETO", "es": "mi bicicleta"},
    "BILLETERA": {"rol": "OBJETO", "es": "mi billetera"},
    "BILLETES": {"rol": "OBJETO", "es": "billetes y dinero"},
    "BOCA": {"rol": "OBJETO", "es": "la boca"},
    "BOLSA": {"rol": "OBJETO", "es": "mi bolsa"},
    "BRAZO": {"rol": "OBJETO", "es": "el brazo"},
    "BUENO": {"rol": "DESCRIPTOR", "es": "bueno"},
    "BUENOS_DIAS": {"rol": "DESCONOCIDO", "es": "buenos días"},
    "BURLAR": {"rol": "VERBO", "es": "se burlaron"},
    "BUSCAR": {"rol": "VERBO", "es": "quiero buscar"},
    "C": {"rol": "VERBO", "es": "c"},
    "CABELLO": {"rol": "OBJETO", "es": "el cabello"},
    "CADA_DIA": {"rol": "TIEMPO", "es": "cada día"},
    "CAJA": {"rol": "OBJETO", "es": "la caja"},
    "CALLE": {"rol": "LUGAR", "es": "en la calle"},
    "CAMARA_FOTOGRAFICA": {"rol": "OBJETO", "es": "una cámara fotográfica"},
    "CAMBIAR": {"rol": "VERBO", "es": "cambié"},
    "CARNET": {"rol": "DESCONOCIDO", "es": "mi carnet de identidad"},
    "CARO": {"rol": "DESCRIPTOR", "es": "costoso"},
    "CARPETA": {"rol": "DOCUMENTO", "es": "la carpeta de documentos"},
    "CASA": {"rol": "LUGAR", "es": "en mi casa"},
    "CELULAR": {"rol": "OBJETO", "es": "mi celular"},
    "CENTRO_DE_SALUD": {"rol": "LUGAR", "es": "en el centro de salud"},
    "CERCA": {"rol": "LUGAR", "es": "cerca"},
    "CERTIFICADO": {"rol": "DOCUMENTO", "es": "un certificado"},
    "CHAMARRA": {"rol": "OBJETO", "es": "mi chamarra"},
    "COCHABAMBA": {"rol": "LUGAR", "es": "en Cochabamba"},
    "COMO": {"rol": "DESCONOCIDO", "es": "cómo"},
    "COMPAÑERO": {"rol": "DESCRIPTOR", "es": "un compañero", "persona": True},
    "COMPRAR": {"rol": "VERBO", "es": "compré"},
    "COMPRENDER": {"rol": "DESCONOCIDO", "es": "comprender"},
    "COMPROBANTE": {"rol": "OBJETO", "es": "un comprobante"},
    "COMPUTADORA": {"rol": "OBJETO", "es": "una computadora"},
    "COMUNIDAD_SORDA": {"rol": "DESCRIPTOR", "es": "la comunidad sorda", "persona": True},
    "CONFIANZA": {"rol": "ESTADO", "es": "tengo confianza"},
    "CONOCER": {"rol": "VERBO", "es": "conozco a esa persona"},
    "CONSTANCIA": {"rol": "DOCUMENTO", "es": "una constancia"},
    "CONTESTAR_DOS_VECES": {"rol": "VERBO", "es": "contesté dos veces"},
    "CONTINUAR": {"rol": "VERBO", "es": "continúa"},
    "CONVOCAR": {"rol": "TRAMITE", "es": "una citación"},
    "COPIAR": {"rol": "VERBO", "es": "copié"},
    "CORRER": {"rol": "VERBO", "es": "salió corriendo", "agresor": "salió corriendo"},
    "CORTO": {"rol": "DESCRIPTOR", "es": "corto"},
    "CREER": {"rol": "VERBO", "es": "creo"},
    "CUAL": {"rol": "DESCONOCIDO", "es": "cuál"},
    "CUANDO": {"rol": "DESCONOCIDO", "es": "cuándo"},
    "CUANTOS": {"rol": "DESCONOCIDO", "es": "cuántos"},
    "CURAR": {"rol": "VERBO", "es": "curar"},
    "D": {"rol": "VERBO", "es": "d"},
    "DAR": {"rol": "VERBO", "es": "entregué"},
    "DAÑAR": {"rol": "VERBO", "es": "dañó", "agresor": "dañó"},
    "DECIDIR": {"rol": "VERBO", "es": "decidí"},
    "DEFENSA_PUBLICA": {"rol": "INSTITUCION", "es": "en la Defensa Pública"},
    "DEJAR": {"rol": "VERBO", "es": "dejé"},
    "DELGADO": {"rol": "DESCRIPTOR", "es": "delgado"},
    "DENTRO": {"rol": "LUGAR", "es": "dentro"},
    "DENUNCIAR": {"rol": "VERBO", "es": "quiero presentar una denuncia"},
    "DESCANSO": {"rol": "TIEMPO", "es": "en horario de descanso"},
    "DESCONOCER": {"rol": "VERBO", "es": "no conozco a esa persona"},
    "DESPUES": {"rol": "TIEMPO", "es": "después"},
    "DEVOLVER": {"rol": "VERBO", "es": "quiero que devuelvan"},
    "DE_NADA": {"rol": "DESCONOCIDO", "es": "de nada"},
    "DIA": {"rol": "TIEMPO", "es": "día"},
    "DIBUJAR": {"rol": "VERBO", "es": "dibujé"},
    "DIFERENTE": {"rol": "DESCRIPTOR", "es": "diferente"},
    "DIFICIL": {"rol": "DESCRIPTOR", "es": "difícil"},
    "DINERO": {"rol": "OBJETO", "es": "mi dinero"},
    "DIRECCION": {"rol": "LUGAR", "es": "en mi dirección"},
    "DISCRIMINACION": {"rol": "DOCUMENTO", "es": "discriminación"},
    "DOCTOR": {"rol": "SERVICIO", "es": "un doctor"},
    "DOLOR": {"rol": "URGENCIA", "es": "dolor físico"},
    "DONDE": {"rol": "DESCONOCIDO", "es": "dónde"},
    "DORMIR": {"rol": "VERBO", "es": "dormía"},
    "DURANTE": {"rol": "TIEMPO", "es": "durante ese tiempo"},
    "E": {"rol": "VERBO", "es": "e"},
    "EDAD": {"rol": "DESCONOCIDO", "es": "tengo esa edad"},
    "EL": {"rol": "SUJETO", "es": "él"},
    "ELLA": {"rol": "SUJETO", "es": "ella"},
    "ELLOS": {"rol": "SUJETO", "es": "ellos"},
    "EMPEZAR": {"rol": "VERBO", "es": "empezó"},
    "ENCONTRARSE": {"rol": "VERBO", "es": "me encontré"},
    "ENFRENTE": {"rol": "LUGAR", "es": "enfrente"},
    "ENGAÑAR": {"rol": "VERBO", "es": "engañó y estafó", "agresor": "engañó y estafó"},
    "ENTREGAR": {"rol": "VERBO", "es": "me entregaron"},
    "ENVIAR": {"rol": "VERBO", "es": "envié"},
    "ESCAPAR": {"rol": "VERBO", "es": "escapó", "agresor": "escapó"},
    "ESCONDER": {"rol": "VERBO", "es": "escondió"},
    "ESCRIBIR": {"rol": "VERBO", "es": "quiero escribir"},
    "ESCUELA": {"rol": "LUGAR", "es": "en la escuela"},
    "ESCUELA_NOCTURNA": {"rol": "LUGAR", "es": "en la escuela nocturna"},
    "ESPERAR": {"rol": "VERBO", "es": "esperar"},
    "ESPOSA": {"rol": "DESCRIPTOR", "es": "mi esposa", "persona": True},
    "ESTADO": {"rol": "TRAMITE", "es": "el estado"},
    "ESTAR_DE_ACUERDO": {"rol": "DESCONOCIDO", "es": "estoy de acuerdo"},
    "EVALUAR": {"rol": "VERBO", "es": "evaluar"},
    "EXPAREJA": {"rol": "DESCRIPTOR", "es": "mi expareja", "persona": True},
    "EXPEDIENTE": {"rol": "DOCUMENTO", "es": "el expediente"},
    "EXPLICAR": {"rol": "VERBO", "es": "quiero explicar"},
    "F": {"rol": "VERBO", "es": "f"},
    "FACTURA": {"rol": "DOCUMENTO", "es": "la factura"},
    "FALTA": {"rol": "VERBO", "es": "perdí"},
    "FECHA": {"rol": "TIEMPO", "es": "en la fecha indicada"},
    "FELCC": {"rol": "INSTITUCION", "es": "en la FELCC"},
    "FELCV": {"rol": "INSTITUCION", "es": "en la FELCV"},
    "FILMAR": {"rol": "VERBO", "es": "filmé"},
    "FISCALIA": {"rol": "INSTITUCION", "es": "en la Fiscalía"},
    "FLACO": {"rol": "DESCRIPTOR", "es": "delgado"},
    "FORMULARIO": {"rol": "DOCUMENTO", "es": "un formulario"},
    "FOTOCOPIA": {"rol": "DOCUMENTO", "es": "una fotocopia"},
    "FOTOGRAFIA": {"rol": "OBJETO", "es": "una fotografía"},
    "FOTOS": {"rol": "OBJETO", "es": "fotografías"},
    "FRACTURA": {"rol": "URGENCIA", "es": "una fractura"},
    "FUERA": {"rol": "LUGAR", "es": "fuera"},
    "FUNCIONAR": {"rol": "VERBO", "es": "funciona"},
    "FUTURO": {"rol": "TIEMPO", "es": "en el futuro"},
    "G": {"rol": "VERBO", "es": "g"},
    "GANAR_DINERO": {"rol": "VERBO", "es": "gané dinero"},
    "GESTIONAR": {"rol": "VERBO", "es": "quiero gestionar"},
    "GOBIERNO": {"rol": "INSTITUCION", "es": "el gobierno"},
    "GORDO": {"rol": "DESCRIPTOR", "es": "de contextura gruesa"},
    "GORRA": {"rol": "OBJETO", "es": "mi gorra"},
    "GRACIAS": {"rol": "DESCONOCIDO", "es": "muchas gracias"},
    "GRATIS": {"rol": "DESCRIPTOR", "es": "gratuito"},
    "GRITAR": {"rol": "VERBO", "es": "gritó"},
    "GRUESO": {"rol": "DESCRIPTOR", "es": "grueso"},
    "GUARDAR": {"rol": "VERBO", "es": "guardé"},
    "H": {"rol": "VERBO", "es": "h"},
    "HABLAR": {"rol": "VERBO", "es": "quiero hablar"},
    "HACER": {"rol": "VERBO", "es": "hice"},
    "HASTA_LUEGO": {"rol": "DESCONOCIDO", "es": "hasta luego"},
    "HASTA_MAÑANA": {"rol": "DESCONOCIDO", "es": "hasta mañana"},
    "HERIDA": {"rol": "URGENCIA", "es": "una herida"},
    "HERMANA": {"rol": "DESCRIPTOR", "es": "mi hermana", "persona": True},
    "HERMANO": {"rol": "DESCRIPTOR", "es": "mi hermano", "persona": True},
    "HIJA": {"rol": "DESCRIPTOR", "es": "mi hija", "persona": True},
    "HIJO": {"rol": "DESCRIPTOR", "es": "mi hijo", "persona": True},
    "HOLA": {"rol": "DESCONOCIDO", "es": "hola"},
    "HOMBRE": {"rol": "DESCRIPTOR", "es": "un hombre", "persona": True},
    "HORA": {"rol": "TIEMPO", "es": "hora"},
    "HOSPITAL": {"rol": "INSTITUCION", "es": "en el hospital"},
    "HOY": {"rol": "TIEMPO", "es": "hoy"},
    "HUESOS": {"rol": "URGENCIA", "es": "los huesos"},
    "I": {"rol": "VERBO", "es": "i"},
    "IDENTIDAD": {"rol": "DESCONOCIDO", "es": "mi carnet de identidad"},
    "IDENTIFICAR": {"rol": "VERBO", "es": "puedo identificar"},
    "IGNORAR": {"rol": "VERBO", "es": "me ignoraron"},
    "INSTITUCION": {"rol": "INSTITUCION", "es": "en la institución"},
    "INTERNET": {"rol": "OBJETO", "es": "por internet"},
    "INTERPRETE": {"rol": "SERVICIO", "es": "un intérprete de LSB"},
    "INVESTIGACION": {"rol": "TRAMITE", "es": "la investigación de mi caso"},
    "IR": {"rol": "VERBO", "es": "fui"},
    "J": {"rol": "VERBO", "es": "j"},
    "JAMAS": {"rol": "TIEMPO", "es": "jamás"},
    "JEFE": {"rol": "DESCRIPTOR", "es": "mi jefe", "persona": True},
    "JOVEN": {"rol": "DESCRIPTOR", "es": "joven", "persona": True},
    "JUEVES": {"rol": "TIEMPO", "es": "el jueves"},
    "JUEZ": {"rol": "INSTITUCION", "es": "el juez"},
    "JULIO": {"rol": "TIEMPO", "es": "en julio"},
    "JUSTICIA": {"rol": "DOCUMENTO", "es": "la justicia"},
    "JUZGADO": {"rol": "INSTITUCION", "es": "en el juzgado"},
    "K": {"rol": "VERBO", "es": "k"},
    "L": {"rol": "VERBO", "es": "l"},
    "LADRON": {"rol": "DESCRIPTOR", "es": "un ladrón", "persona": True},
    "LEER": {"rol": "VERBO", "es": "quiero leer"},
    "LEJOS": {"rol": "LUGAR", "es": "lejos"},
    "LENTES": {"rol": "OBJETO", "es": "mis lentes"},
    "LENTO": {"rol": "DESCRIPTOR", "es": "despacio"},
    "LEY": {"rol": "DOCUMENTO", "es": "la ley"},
    "LIBRE": {"rol": "TIEMPO", "es": "libre"},
    "LISTA": {"rol": "DOCUMENTO", "es": "la lista"},
    "LLAMAR": {"rol": "VERBO", "es": "llamé"},
    "LLEGAR": {"rol": "VERBO", "es": "llegué"},
    "LLEVAR": {"rol": "VERBO", "es": "llevaba"},
    "LO_SIENTO": {"rol": "DESCONOCIDO", "es": "lo siento"},
    "LUEGO": {"rol": "TIEMPO", "es": "luego"},
    "LUNES": {"rol": "TIEMPO", "es": "el lunes"},
    "M": {"rol": "VERBO", "es": "m"},
    "MAL": {"rol": "DESCRIPTOR", "es": "mal"},
    "MALTRATAR": {"rol": "VERBO", "es": "maltrató", "agresor": "maltrató"},
    "MAMA": {"rol": "DESCRIPTOR", "es": "mi mamá", "persona": True},
    "MARTES": {"rol": "TIEMPO", "es": "el martes"},
    "MARZO": {"rol": "TIEMPO", "es": "en marzo"},
    "MAS_O_MENOS": {"rol": "DESCONOCIDO", "es": "más o menos"},
    "MAÑANA": {"rol": "TIEMPO", "es": "mañana"},
    "MEDICINA": {"rol": "OBJETO", "es": "medicinas"},
    "MEJOR": {"rol": "DESCRIPTOR", "es": "mejor"},
    "MEMORIAL": {"rol": "DOCUMENTO", "es": "un memorial"},
    "MENSAJE": {"rol": "OBJETO", "es": "un mensaje"},
    "MENTIRA": {"rol": "DESCONOCIDO", "es": "es mentira"},
    "MERCADO": {"rol": "LUGAR", "es": "en el mercado"},
    "MES": {"rol": "TIEMPO", "es": "mes"},
    "MICRO": {"rol": "OBJETO", "es": "un micro"},
    "MIEDO": {"rol": "ESTADO", "es": "tengo miedo"},
    "MILITAR": {"rol": "DESCRIPTOR", "es": "un militar", "persona": True},
    "MINUTO": {"rol": "TIEMPO", "es": "minuto"},
    "MIO": {"rol": "SUJETO", "es": "mi"},
    "MIRAR": {"rol": "VERBO", "es": "vi"},
    "MOCHILA": {"rol": "OBJETO", "es": "mi mochila"},
    "MOMENTO": {"rol": "TIEMPO", "es": "en ese momento"},
    "MOSTRAR": {"rol": "VERBO", "es": "puedo mostrar"},
    "MOTOCICLETA": {"rol": "OBJETO", "es": "mi motocicleta"},
    "MUCHO": {"rol": "DESCRIPTOR", "es": "mucho"},
    "MUJER": {"rol": "DESCRIPTOR", "es": "una mujer", "persona": True},
    "N": {"rol": "VERBO", "es": "n"},
    "NARRAR": {"rol": "VERBO", "es": "quiero relatar"},
    "NECESITAR": {"rol": "VERBO", "es": "necesitar"},
    "NEGRO": {"rol": "DESCRIPTOR", "es": "de color negro"},
    "NO": {"rol": "DESCONOCIDO", "es": "no"},
    "NOMBRE": {"rol": "DESCONOCIDO", "es": "mi nombre es"},
    "NOSOTROS": {"rol": "SUJETO", "es": "nosotros"},
    "NOTIFICACION": {"rol": "DOCUMENTO", "es": "la notificación"},
    "NO_ENTIENDO": {"rol": "DESCONOCIDO", "es": "no entiendo"},
    "NO_ESTAR_DE_ACUERDO": {"rol": "DESCONOCIDO", "es": "no estoy de acuerdo"},
    "NO_PUEDO": {"rol": "DESCONOCIDO", "es": "no puedo"},
    "NO_RECUERDO": {"rol": "DESCONOCIDO", "es": "no recuerdo"},
    "NO_SABER": {"rol": "DESCONOCIDO", "es": "no sé"},
    "NUEVO": {"rol": "DESCRIPTOR", "es": "nuevo"},
    "NUREJ": {"rol": "DOCUMENTO", "es": "el NUREJ"},
    "O": {"rol": "VERBO", "es": "o"},
    "OBSERVACION": {"rol": "DOCUMENTO", "es": "una observación"},
    "OBSERVAR": {"rol": "VERBO", "es": "observé"},
    "OCUPADO": {"rol": "TIEMPO", "es": "ocupado"},
    "OFICIAL": {"rol": "SERVICIO", "es": "un oficial"},
    "OFICINA": {"rol": "LUGAR", "es": "en la oficina"},
    "OIR": {"rol": "VERBO", "es": "escuché"},
    "ORGANIZAR": {"rol": "VERBO", "es": "organicé"},
    "ORGANO_JUDICIAL": {"rol": "INSTITUCION", "es": "en el Órgano Judicial"},
    "OSCURO": {"rol": "DESCRIPTOR", "es": "oscuro"},
    "OYENTE": {"rol": "DESCRIPTOR", "es": "oyente", "persona": True},
    "P": {"rol": "VERBO", "es": "p"},
    "PAGAR": {"rol": "VERBO", "es": "pagué"},
    "PAGINA": {"rol": "DOCUMENTO", "es": "la página"},
    "PALABRA": {"rol": "VERBO", "es": "palabra"},
    "PANTALON": {"rol": "OBJETO", "es": "mi pantalón"},
    "PAPEL": {"rol": "DOCUMENTO", "es": "el documento"},
    "PARADA": {"rol": "LUGAR", "es": "en la parada"},
    "PAREJA": {"rol": "DESCRIPTOR", "es": "mi pareja", "persona": True},
    "PARIENTE": {"rol": "DESCRIPTOR", "es": "un pariente", "persona": True},
    "PASADO": {"rol": "TIEMPO", "es": "en el pasado"},
    "PASADO_MAÑANA": {"rol": "TIEMPO", "es": "pasado mañana"},
    "PASAPORTE": {"rol": "DOCUMENTO", "es": "mi pasaporte"},
    "PEDIR": {"rol": "VERBO", "es": "solicito"},
    "PEGAR": {"rol": "VERBO", "es": "golpeó y pegó", "agresor": "golpeó y pegó"},
    "PELEAR": {"rol": "VERBO", "es": "inició una pelea", "agresor": "inició una pelea"},
    "PERDER": {"rol": "VERBO", "es": "perdí"},
    "PERMISO": {"rol": "DESCONOCIDO", "es": "con permiso"},
    "PLAZA": {"rol": "LUGAR", "es": "en la plaza"},
    "PLAZO": {"rol": "TRAMITE", "es": "el plazo"},
    "POCO": {"rol": "DESCRIPTOR", "es": "poco"},
    "POLERA": {"rol": "OBJETO", "es": "mi polera"},
    "POLICIA": {"rol": "INSTITUCION", "es": "en la policía"},
    "POR_FAVOR": {"rol": "DESCONOCIDO", "es": "por favor"},
    "POSTERGAR": {"rol": "TIEMPO", "es": "postergar"},
    "PREOCUPAR": {"rol": "ESTADO", "es": "estoy preocupado"},
    "PRESENTAR": {"rol": "VERBO", "es": "quiero presentar"},
    "PRIMERA_VEZ": {"rol": "TIEMPO", "es": "la primera vez"},
    "PRODUCTO": {"rol": "OBJETO", "es": "el producto"},
    "PROHIBIDO": {"rol": "DOCUMENTO", "es": "prohibido"},
    "PROTEGER": {"rol": "VERBO", "es": "necesito protección"},
    "PROVINCIA": {"rol": "LUGAR", "es": "en la provincia"},
    "PROXIMO": {"rol": "TIEMPO", "es": "el próximo"},
    "PUEDO": {"rol": "DESCONOCIDO", "es": "puedo"},
    "PUERTA": {"rol": "OBJETO", "es": "la puerta"},
    "Q": {"rol": "VERBO", "es": "q"},
    "QUE": {"rol": "DESCONOCIDO", "es": "qué"},
    "QUEJAR": {"rol": "VERBO", "es": "quejar"},
    "QUERER": {"rol": "VERBO", "es": "querer"},
    "QUIEN": {"rol": "DESCONOCIDO", "es": "quién"},
    "R": {"rol": "VERBO", "es": "r"},
    "RAYOS_X": {"rol": "OBJETO", "es": "placas de rayos X"},
    "RECHAZAR": {"rol": "VERBO", "es": "rechazo"},
    "RECIBIR": {"rol": "VERBO", "es": "recibí"},
    "RECORDAR": {"rol": "VERBO", "es": "recuerdo"},
    "RESOLUCION": {"rol": "DOCUMENTO", "es": "una resolución"},
    "RESPALDO": {"rol": "OBJETO", "es": "un respaldo"},
    "RESULTADO": {"rol": "DOCUMENTO", "es": "el resultado"},
    "REUNION": {"rol": "VERBO", "es": "reunión"},
    "ROBAR": {"rol": "VERBO", "es": "robó", "agresor": "robó"},
    "ROJO": {"rol": "DESCRIPTOR", "es": "de color rojo"},
    "S": {"rol": "VERBO", "es": "s"},
    "SABADO": {"rol": "TIEMPO", "es": "el sábado"},
    "SABER": {"rol": "DESCONOCIDO", "es": "sé"},
    "SEGUNDO": {"rol": "TIEMPO", "es": "segundo"},
    "SEGURO": {"rol": "ESTADO", "es": "me encuentro en un lugar seguro"},
    "SELLO": {"rol": "DOCUMENTO", "es": "un sello oficial"},
    "SEMANA": {"rol": "TIEMPO", "es": "semana"},
    "SEPARADOS": {"rol": "DESCRIPTOR", "es": "separados", "persona": True},
    "SEPDAVI": {"rol": "INSTITUCION", "es": "en el SEPDAVI"},
    "SEPDEP": {"rol": "INSTITUCION", "es": "en el SEPDEP"},
    "SEÑOR": {"rol": "DESCRIPTOR", "es": "el señor", "persona": True},
    "SI": {"rol": "DESCONOCIDO", "es": "sí"},
    "SIEMPRE": {"rol": "TIEMPO", "es": "siempre"},
    "SOLUCIONAR": {"rol": "VERBO", "es": "quiero solucionar"},
    "SOPORTE": {"rol": "DOCUMENTO", "es": "soporte"},
    "SORDO": {"rol": "DESCRIPTOR", "es": "una persona sorda", "persona": True},
    "SOSPECHA": {"rol": "ESTADO", "es": "tengo una sospecha"},
    "SUYO": {"rol": "SUJETO", "es": "suyo"},
    "T": {"rol": "VERBO", "es": "t"},
    "TAL_VEZ": {"rol": "DESCONOCIDO", "es": "tal vez"},
    "TARDE": {"rol": "TIEMPO", "es": "por la tarde"},
    "TAXI": {"rol": "OBJETO", "es": "un taxi"},
    "TELEFONO": {"rol": "OBJETO", "es": "mi teléfono"},
    "TEMOR": {"rol": "ESTADO", "es": "tengo temor"},
    "TEMPRANO": {"rol": "TIEMPO", "es": "temprano"},
    "TENER": {"rol": "VERBO", "es": "tener"},
    "TERMINAR": {"rol": "VERBO", "es": "terminó"},
    "TESTIGO": {"rol": "TESTIGO", "es": "un testigo"},
    "TESTIMONIO": {"rol": "DOCUMENTO", "es": "mi testimonio"},
    "TIENDA": {"rol": "LUGAR", "es": "en la tienda"},
    "TODOS_LOS_DIAS": {"rol": "TIEMPO", "es": "todos los días"},
    "TOTAL": {"rol": "VERBO", "es": "total"},
    "TRABAJADOR": {"rol": "DESCRIPTOR", "es": "un trabajador", "persona": True},
    "TRAER": {"rol": "VERBO", "es": "puedo traer"},
    "TRAMITE": {"rol": "TRAMITE", "es": "un trámite"},
    "TRISTE": {"rol": "ESTADO", "es": "estoy triste"},
    "TRUFI": {"rol": "OBJETO", "es": "un trufi"},
    "TU": {"rol": "SUJETO", "es": "tú"},
    "TUYO": {"rol": "SUJETO", "es": "su"},
    "U": {"rol": "VERBO", "es": "u"},
    "ULTIMO": {"rol": "TIEMPO", "es": "el último"},
    "URGENTE": {"rol": "URGENCIA", "es": "de manera urgente"},
    "V": {"rol": "VERBO", "es": "v"},
    "VARIOS": {"rol": "SUJETO", "es": "varios"},
    "VECINO": {"rol": "DESCRIPTOR", "es": "un vecino", "persona": True},
    "VENDER": {"rol": "VERBO", "es": "vendí"},
    "VENIR": {"rol": "VERBO", "es": "vine"},
    "VENTANILLA": {"rol": "LUGAR", "es": "en la ventanilla"},
    "VER": {"rol": "VERBO", "es": "vi"},
    "VERDAD": {"rol": "DESCONOCIDO", "es": "es verdad"},
    "VIDEO": {"rol": "OBJETO", "es": "un video"},
    "VIDEOLLAMADA": {"rol": "OBJETO", "es": "una videollamada"},
    "VIERNES": {"rol": "TIEMPO", "es": "el viernes"},
    "VIOLENCIA": {"rol": "URGENCIA", "es": "un hecho de violencia"},
    "VIVIR": {"rol": "VERBO", "es": "vivo"},
    "VOLVER": {"rol": "VERBO", "es": "debo volver"},
    "W": {"rol": "VERBO", "es": "w"},
    "WHATSAPP": {"rol": "OBJETO", "es": "por WhatsApp"},
    "X": {"rol": "VERBO", "es": "x"},
    "Y": {"rol": "VERBO", "es": "y"},
    "YO": {"rol": "SUJETO", "es": "yo"},
    "Z": {"rol": "VERBO", "es": "z"},
    "Ñ": {"rol": "VERBO", "es": "ñ"},
}
