import 'package:lsb_legal_app/core/domain/entities/semantic_context.dart';
import 'package:lsb_legal_app/core/domain/entities/semantic_zone.dart';
import 'package:lsb_legal_app/core/domain/services/local_sentence_assembler.dart' show kVictimMarker, kEvidenceMarker, kVehicleMarker;

final preguntasContext = SemanticContext(
  id: 'preguntas',
  name: 'Preguntas',
  icon: 'question_answer',
  emoji: '❓',
  description: 'Quiero preguntar algo',
  entryZoneId: 'interrogativa',
  zones: const [
    SemanticZone(
      id: 'interrogativa',
      label: 'Pregunta',
      hint: 'Qué quiero preguntar',
      question: '¿Qué quieres preguntar?',
      emoji: '❓',
      semanticWeight: 0.95,
      glossAllowlist: [
        'DONDE', 'QUIEN', 'QUE', 'CUANDO', 'CUAL',
        'COMO', 'CUANTOS', 'POR_QUE', 'PARA_QUE',
      ],
      relatedZones: ['lugar_pregunta', 'persona_pregunta', 'tema_pregunta'],
    ),
    SemanticZone(
      id: 'lugar_pregunta',
      label: 'Lugar',
      hint: 'De qué lugar pregunto',
      question: '¿Dónde está…?',
      emoji: '📍',
      semanticWeight: 0.8,
      optional: true,
      glossAllowlist: [
        'FISCALIA', 'FELCC', 'FELCV', 'JUZGADO',
        'DEFENSA_PUBLICA', 'SEPAV', 'TRIBUNAL',
        'OFICINA', 'VENTANILLA', 'DESPACHO', 'HOSPITAL',
      ],
    ),
    SemanticZone(
      id: 'persona_pregunta',
      label: 'Persona',
      hint: 'Por quién pregunto',
      question: '¿Quién es…?',
      emoji: '👤',
      semanticWeight: 0.8,
      optional: true,
      glossAllowlist: [
        'FISCAL', 'JUEZ', 'ABOGADO', 'INTERPRETE',
        'AUTORIDAD', 'DOCTOR', 'COORDINADOR',
      ],
    ),
    SemanticZone(
      id: 'tema_pregunta',
      label: 'Trámite o documento',
      hint: 'Por qué gestión pregunto',
      question: '¿Qué documento o trámite?',
      emoji: '📋',
      semanticWeight: 0.8,
      optional: true,
      glossAllowlist: [
        'TRAMITE', 'REQUISITO', 'CASO', 'EXPEDIENTE', 'AVANCE', 'ESTADO',
        'DENUNCIAR',
        'CARNET', 'PASAPORTE', 'CERTIFICADO', 'CONSTANCIA', 'FORMULARIO',
      ],
    ),
    SemanticZone(
      id: 'tiempo_pregunta',
      label: 'Cuándo',
      hint: 'Por qué fecha pregunto',
      question: '¿Cuándo es…?',
      emoji: '🕐',
      semanticWeight: 0.7,
      optional: true,
      glossAllowlist: [
        'AUDIENCIA', 'CITACION', 'NOTIFICACION', 'VOLVER',
        'DIA', 'SEMANA', 'MES',
      ],
      chainTriggers: ['DIA', 'SEMANA', 'MES'],
      chainZoneId: 'cantidad_pregunta',
    ),
    SemanticZone(
      id: 'cantidad_pregunta',
      label: 'Cuántos',
      hint: 'Cantidad',
      question: '¿Cuántos?',
      emoji: '🔢',
      semanticWeight: 0.3,
      optional: true,
      glossAllowlist: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
    ),
  ],
);

final identificacionContext = SemanticContext(
  id: 'identificacion',
  name: 'Mis datos',
  icon: 'badge',
  emoji: '🪪',
  description: 'Mi nombre, mi edad y mi documento',
  entryZoneId: 'identidad',
  zones: const [
    SemanticZone(
      id: 'identidad',
      label: 'Identidad',
      hint: 'Mi nombre, mi apellido y mi documento',
      question: '¿Cuál es su nombre?',
      emoji: '🪪',
      semanticWeight: 0.95,
      maxPicks: 3,
      glossAllowlist: ['NOMBRE', 'APELLIDO', 'CARNET', 'IDENTIDAD'],
      relatedZones: ['edad'],
    ),
    SemanticZone(
      id: 'edad',
      label: 'Edad',
      hint: 'Qué edad tengo',
      question: '¿Qué edad tiene?',
      emoji: '🎂',
      semanticWeight: 0.9,
      glossAllowlist: ['EDAD', 'ANOS_EDAD'],
    ),
  ],
);

final availableContexts = <SemanticContext>[
  SemanticContext(
    id: 'denuncia_robo',
    name: 'Denunciar robo',
    icon: 'warning_amber',
    emoji: '🚨',
    description: 'Me robaron / Hurto / Asalto',
    entryZoneId: 'situacion',
    baseUrgency: UrgencyLevel.medium,
    zones: const [
      SemanticZone(
        id: 'situacion',
        label: 'Situación',
        hint: 'Qué pasó',
        question: '¿Qué pasó?',
        emoji: '⚡',
        semanticWeight: 0.9,
        glossAllowlist: ['ROBAR', 'AMENAZAR', 'DANAR', 'CORRER', 'SOBORNO'],
        contextTags: [EmotionalTag.amenaza],
        relatedZones: ['agravante', 'personas', 'objetos', 'emergencia'],
      ),
      SemanticZone(
        id: 'agravante',
        label: 'Agravante',
        hint: '¿Te amenazó o te hizo daño?',
        question: '¿Te amenazó o te hizo daño?',
        emoji: '⚠️',
        semanticWeight: 0.7,
        optional: true,
        glossAllowlist: ['AMENAZAR', 'DANAR', 'VIOLENCIA', 'HERIDA'],
        contextTags: [EmotionalTag.amenaza, EmotionalTag.peligro],
        relatedZones: ['personas', 'objetos'],
      ),
      SemanticZone(
        id: 'personas',
        label: 'Quién',
        hint: 'Tipo de persona',
        question: '¿Quién te robó?',
        emoji: '👤',
        semanticWeight: 0.85,
        maxPicks: 2,
        glossAllowlist: ['HOMBRE', 'MUJER', 'VECINO', 'MILITAR', 'SOLDADO'],
        relatedZones: ['apariencia', 'objetos'],
      ),
      SemanticZone(
        id: 'apariencia',
        label: 'Apariencia',
        hint: 'Cómo era físicamente',
        question: '¿Cómo era la persona?',
        emoji: '🧍',
        semanticWeight: 0.6,
        optional: true,
        maxPicks: 2,
        glossAllowlist: ['DELGADO', 'GRUESO'],
        relatedZones: ['personas'],
      ),
      SemanticZone(
        id: 'objetos',
        label: 'Objetos',
        hint: 'Qué se llevaron',
        question: '¿Qué se llevaron?',
        emoji: '📱',
        semanticWeight: 0.8,
        maxPicks: 3,
        glossAllowlist: [
          'TELEFONO', 'MOCHILA', 'DINERO', 'BILLETERA', 'CARNET',
          'BICICLETA', 'CAMARA',
          'PASAPORTE', 'LICENCIA_DECONDUCIR',
        ],
        relatedZones: ['lugar'],
      ),
      SemanticZone(
        id: 'lugar',
        label: 'Lugar',
        hint: 'Dónde fue',
        question: '¿Dónde ocurrió?',
        emoji: '📍',
        semanticWeight: 0.6,
        glossAllowlist: [
          'CALLE', 'AVENIDA', 'PLAZA', 'MERCADO',
          'PARADA', 'CASA', 'AEROPUERTO', 'COCHABAMBA',
        ],
        relatedZones: ['tiempo'],
      ),
      SemanticZone(
        id: 'pruebas',
        label: 'Pruebas',
        hint: 'Qué evidencia tengo',
        question: '¿Tienes pruebas?',
        emoji: '📎',
        semanticWeight: 0.55,
        optional: true,
        maxPicks: 3,
        glossAllowlist: [
          'FOTOGRAFIA', 'MENSAJE', 'CERTIFICADO', 'COMPROBANTE',
          'VIDEOLLAMADA', 'CAMARA',
          'WHATSAPP', 'VIDEOLLAMADA', 'COMPROBANTE', 'CERTIFICADO',
        ],
        leadGloss: kEvidenceMarker,
      ),
      SemanticZone(
        id: 'emergencia',
        label: 'Emergencia',
        hint: 'Estoy en peligro',
        question: '¿Necesitas ayuda urgente?',
        emoji: '🆘',
        semanticWeight: 0.3,
        urgencyLevel: UrgencyLevel.high,
        glossAllowlist: ['AUXILIO', 'ASISTENCIA', 'CRISIS', 'HERIDA'],
        contextTags: [EmotionalTag.urgente, EmotionalTag.ayuda, EmotionalTag.peligro],
        relatedZones: ['situacion'],
      ),
      SemanticZone(
        id: 'tiempo',
        label: 'Tiempo',
        hint: 'Cuándo',
        question: '¿Cuándo pasó?',
        emoji: '🕐',
        semanticWeight: 0.4,
        optional: true,
        glossAllowlist: [
          'AHORA', 'HOY', 'AYER', 'ANTEAYER',
          'MINUTO', 'HORA', 'DIA', 'SEMANA', 'MES',
        ],
        chainTriggers: ['MINUTO', 'HORA', 'DIA', 'SEMANA', 'MES'],
        chainZoneId: 'cantidad',
      ),
      SemanticZone(
        id: 'conocimiento',
        label: 'Conocimiento',
        hint: 'Si conozco a la persona involucrada',
        question: '¿Conoces a la persona?',
        emoji: '🤝',
        semanticWeight: 0.35,
        optional: true,
        glossAllowlist: ['CONOCER', 'DESCONOCER'],
      ),
      SemanticZone(
        id: 'testigos',
        label: 'Testigos',
        hint: 'Si alguien lo presenció',
        question: '¿Hay testigos?',
        emoji: '👀',
        semanticWeight: 0.35,
        optional: true,
        maxPicks: 2,
        glossAllowlist: ['SI', 'NO', 'TESTIGO'],
      ),
      SemanticZone(
        id: 'denuncia',
        label: 'Denuncia',
        hint: 'Si quiero denunciar',
        question: '¿Deseas realizar la denuncia?',
        emoji: '📝',
        semanticWeight: 0.3,
        optional: true,
        maxPicks: 2,
        glossAllowlist: ['SI', 'NO', 'DENUNCIAR'],
      ),
      SemanticZone(
        id: 'apoyo_legal',
        label: 'Apoyo legal',
        hint: 'Si necesito abogado o intérprete',
        question: '¿Necesitas apoyo legal?',
        emoji: '⚖️',
        semanticWeight: 0.3,
        optional: true,
        maxPicks: 2,
        glossAllowlist: ['ABOGADO', 'DEFENSA_PUBLICA', 'INTERPRETE'],
      ),
      SemanticZone(
        id: 'cantidad',
        label: 'Cuántos',
        hint: 'Cantidad',
        question: '¿Cuántos?',
        emoji: '🔢',
        semanticWeight: 0.25,
        optional: true,
        glossAllowlist: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
      ),
    ],
  ),

  SemanticContext(
    id: 'violencia',
    name: 'Denunciar violencia',
    icon: 'shield',
    emoji: '🛡️',
    description: 'Me agredieron / Me amenazaron / Abuso',
    entryZoneId: 'situacion',
    baseUrgency: UrgencyLevel.high,
    zones: const [
      SemanticZone(
        id: 'situacion',
        label: 'Situación',
        hint: 'Qué pasó',
        question: '¿Qué te hicieron?',
        emoji: '⚡',
        semanticWeight: 0.95,
        urgencyLevel: UrgencyLevel.medium,
        glossAllowlist: [
          'MALTRATAR', 'AMENAZAR', 'ABUSAR', 'VIOLACION',
          'DISCRIMINACION', 'VIOLENCIA', 'DANAR',
        ],
        contextTags: [EmotionalTag.amenaza, EmotionalTag.peligro],
        relatedZones: ['personas', 'reincidencia', 'emocion', 'emergencia'],
      ),
      SemanticZone(
        id: 'personas',
        label: 'Quién',
        hint: 'Tipo de persona',
        question: '¿Quién te agredió?',
        emoji: '👤',
        semanticWeight: 0.85,
        maxPicks: 2,
        glossAllowlist: [
          'PAREJA', 'EXPAREJA', 'FAMILIAR', 'VECINO',
          'HOMBRE', 'MUJER', 'MILITAR', 'SOLDADO',
        ],
        relatedZones: ['apariencia', 'reincidencia'],
      ),
      SemanticZone(
        id: 'apariencia',
        label: 'Apariencia',
        hint: 'Cómo era físicamente',
        question: '¿Cómo era la persona?',
        emoji: '🧍',
        semanticWeight: 0.5,
        optional: true,
        maxPicks: 2,
        glossAllowlist: ['DELGADO', 'GRUESO'],
      ),
      SemanticZone(
        id: 'reincidencia',
        label: 'Reincidencia',
        hint: 'Si ya había pasado',
        question: '¿Es la primera vez o ya había pasado?',
        emoji: '🔁',
        semanticWeight: 0.75,
        glossAllowlist: ['PRIMERA_VEZ', 'VARIAS_VECES', 'ANTERIORMENTE'],
        relatedZones: ['emocion'],
      ),
      SemanticZone(
        id: 'emocion',
        label: 'Cómo me siento',
        hint: 'Estado emocional',
        question: '¿Cómo te sientes?',
        emoji: '💔',
        semanticWeight: 0.7,
        glossAllowlist: ['MIEDO', 'TEMOR', 'MAL', 'VERGUENZA', 'CONFUSION'],
        contextTags: [EmotionalTag.miedo, EmotionalTag.dolor],
        relatedZones: ['seguridad', 'emergencia'],
      ),
      SemanticZone(
        id: 'seguridad',
        label: 'Seguridad',
        hint: 'Si estoy a salvo',
        question: '¿Estás en un lugar seguro?',
        emoji: '🏠',
        semanticWeight: 0.68,
        optional: true,
        glossAllowlist: ['SEGURO', 'CASA', 'FAMILIAR'],
      ),
      SemanticZone(
        id: 'pruebas',
        label: 'Pruebas',
        hint: 'Qué evidencia tengo',
        question: '¿Tienes pruebas?',
        emoji: '📎',
        semanticWeight: 0.6,
        optional: true,
        maxPicks: 3,
        glossAllowlist: [
          'MENSAJE', 'FOTOGRAFIA', 'CERTIFICADO', 'COMPROBANTE',
          'VIDEOLLAMADA', 'WHATSAPP',
          'VIDEOLLAMADA', 'CERTIFICADO', 'CAMARA',
        ],
        leadGloss: kEvidenceMarker,
      ),
      SemanticZone(
        id: 'emergencia',
        label: 'Necesito ayuda',
        hint: 'Estoy en peligro',
        question: '¿Necesitas ayuda urgente?',
        emoji: '🆘',
        semanticWeight: 0.5,
        urgencyLevel: UrgencyLevel.critical,
        glossAllowlist: ['AUXILIO', 'ASISTENCIA', 'CRISIS', 'HERIDA'],
        contextTags: [EmotionalTag.urgente, EmotionalTag.ayuda],
        relatedZones: ['salud'],
      ),
      SemanticZone(
        id: 'salud',
        label: 'Salud',
        hint: 'Atención médica',
        question: '¿Necesitas atención médica?',
        emoji: '🏥',
        semanticWeight: 0.58,
        optional: true,
        glossAllowlist: ['HOSPITAL', 'CENTRO_DE_SALUD', 'DOCTOR', 'ENFERMERA', 'HERIDA'],
      ),
      SemanticZone(
        id: 'lugar',
        label: 'Lugar',
        hint: 'Dónde fue',
        question: '¿Dónde ocurrió?',
        emoji: '📍',
        semanticWeight: 0.55,
        glossAllowlist: [
          'CASA', 'CALLE', 'AVENIDA', 'PLAZA',
          'MERCADO', 'PARADA', 'COCHABAMBA',
        ],
      ),
      SemanticZone(
        id: 'institucion',
        label: 'Institución',
        hint: 'A dónde acudir',
        question: '¿A qué institución quieres acudir?',
        emoji: '🏛️',
        semanticWeight: 0.5,
        optional: true,
        glossAllowlist: [
          'POLICIA', 'FISCAL', 'ORGANO_JUDICIAL', 'ALCALDIA', 'MINISTERIO',
        ],
      ),
      SemanticZone(
        id: 'tiempo',
        label: 'Tiempo',
        hint: 'Cuándo',
        question: '¿Cuándo pasó?',
        emoji: '🕐',
        semanticWeight: 0.35,
        optional: true,
        glossAllowlist: [
          'AHORA', 'HOY', 'AYER', 'ANTEAYER',
          'MINUTO', 'HORA', 'DIA', 'SEMANA', 'MES',
        ],
        chainTriggers: ['MINUTO', 'HORA', 'DIA', 'SEMANA', 'MES'],
        chainZoneId: 'cantidad',
      ),
      SemanticZone(
        id: 'conocimiento',
        label: 'Conocimiento',
        hint: 'Si conozco a la persona involucrada',
        question: '¿Conoces a la persona?',
        emoji: '🤝',
        semanticWeight: 0.35,
        optional: true,
        glossAllowlist: ['CONOCER', 'DESCONOCER'],
      ),
      SemanticZone(
        id: 'testigos',
        label: 'Testigos',
        hint: 'Si alguien lo presenció',
        question: '¿Hay testigos?',
        emoji: '👀',
        semanticWeight: 0.35,
        optional: true,
        maxPicks: 2,
        glossAllowlist: ['SI', 'NO', 'TESTIGO'],
      ),
      SemanticZone(
        id: 'denuncia',
        label: 'Denuncia',
        hint: 'Si quiero denunciar',
        question: '¿Deseas realizar la denuncia?',
        emoji: '📝',
        semanticWeight: 0.3,
        optional: true,
        maxPicks: 2,
        glossAllowlist: ['SI', 'NO', 'DENUNCIAR'],
      ),
      SemanticZone(
        id: 'apoyo_legal',
        label: 'Apoyo legal',
        hint: 'Si necesito abogado o intérprete',
        question: '¿Necesitas apoyo legal?',
        emoji: '⚖️',
        semanticWeight: 0.3,
        optional: true,
        maxPicks: 2,
        glossAllowlist: ['ABOGADO', 'DEFENSA_PUBLICA', 'INTERPRETE'],
      ),
      SemanticZone(
        id: 'cantidad',
        label: 'Cuántos',
        hint: 'Cantidad',
        question: '¿Cuántos?',
        emoji: '🔢',
        semanticWeight: 0.25,
        optional: true,
        glossAllowlist: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
      ),
    ],
  ),

  SemanticContext(
    id: 'accidente',
    name: 'Reportar accidente',
    icon: 'car_crash',
    emoji: '🚗',
    description: 'Tránsito / Caída / Lesión / Emergencia médica',
    entryZoneId: 'estado',
    baseUrgency: UrgencyLevel.high,
    zones: const [
      SemanticZone(
        id: 'estado',
        label: 'Cómo estoy',
        hint: 'Estado físico',
        question: '¿Cómo te encuentras?',
        emoji: '💔',
        semanticWeight: 0.85,
        urgencyLevel: UrgencyLevel.high,
        glossAllowlist: ['MAL', 'HERIDA', 'CRISIS', 'CONFUSION'],
        contextTags: [EmotionalTag.dolor, EmotionalTag.urgente],
        relatedZones: ['ayuda', 'vehiculo'],
      ),
      SemanticZone(
        id: 'vehiculo',
        label: 'Vehículo',
        hint: 'Qué vehículo',
        question: '¿Qué vehículo estuvo involucrado?',
        emoji: '🚗',
        semanticWeight: 0.75,
        maxPicks: 2,
        glossAllowlist: [
          'AUTO', 'MOTOCICLETA', 'BICICLETA', 'MICRO', 'TAXI', 'TRUFI', 'TREN',
        ],
        leadGloss: kVehicleMarker,
        relatedZones: ['lugar'],
      ),
      SemanticZone(
        id: 'ayuda',
        label: 'Ayuda',
        hint: 'Qué necesito',
        question: '¿Qué ayuda necesitas?',
        emoji: '🚑',
        semanticWeight: 0.7,
        urgencyLevel: UrgencyLevel.high,
        glossAllowlist: ['AUXILIO', 'ASISTENCIA', 'DOCTOR', 'ENFERMERA'],
        contextTags: [EmotionalTag.urgente, EmotionalTag.ayuda],
        relatedZones: ['salud'],
      ),
      SemanticZone(
        id: 'salud',
        label: 'Salud',
        hint: 'Hospital o centro de salud',
        question: '¿Necesitas atención médica?',
        emoji: '🏥',
        semanticWeight: 0.58,
        optional: true,
        glossAllowlist: ['HOSPITAL', 'CENTRO_DE_SALUD', 'FARMACIA'],
      ),
      SemanticZone(
        id: 'personas',
        label: 'Personas',
        hint: 'Quién estuvo',
        question: '¿A quién más le ocurrió?',
        emoji: '👤',
        semanticWeight: 0.5,
        maxPicks: 2,
        glossAllowlist: ['HOMBRE', 'MUJER', 'FAMILIAR', 'PAREJA', 'VECINO', 'TESTIGO'],
      ),
      SemanticZone(
        id: 'lugar',
        label: 'Lugar',
        hint: 'Dónde fue',
        question: '¿Dónde ocurrió?',
        emoji: '📍',
        semanticWeight: 0.5,
        glossAllowlist: ['CALLE', 'AVENIDA', 'PLAZA', 'MERCADO', 'PARADA', 'COCHABAMBA'],
      ),
      SemanticZone(
        id: 'institucion',
        label: 'Institución',
        hint: 'A dónde acudir',
        question: '¿A qué institución acudiste?',
        emoji: '🏛️',
        semanticWeight: 0.45,
        optional: true,
        glossAllowlist: ['POLICIA', 'HOSPITAL', 'ALCALDIA', 'FISCAL'],
      ),
      SemanticZone(
        id: 'tiempo',
        label: 'Tiempo',
        hint: 'Cuándo',
        question: '¿Cuándo ocurrió?',
        emoji: '🕐',
        semanticWeight: 0.35,
        optional: true,
        glossAllowlist: [
          'AHORA', 'HOY', 'AYER', 'ANTEAYER',
          'MINUTO', 'HORA', 'DIA', 'SEMANA', 'MES',
        ],
        chainTriggers: ['MINUTO', 'HORA', 'DIA', 'SEMANA', 'MES'],
        chainZoneId: 'cantidad',
      ),
      SemanticZone(
        id: 'testigos',
        label: 'Testigos',
        hint: 'Si alguien lo presenció',
        question: '¿Hay testigos?',
        emoji: '👀',
        semanticWeight: 0.35,
        optional: true,
        maxPicks: 2,
        glossAllowlist: ['SI', 'NO', 'TESTIGO'],
      ),
      SemanticZone(
        id: 'apoyo_legal',
        label: 'Apoyo legal',
        hint: 'Si necesito abogado o intérprete',
        question: '¿Necesitas apoyo legal?',
        emoji: '⚖️',
        semanticWeight: 0.3,
        optional: true,
        maxPicks: 2,
        glossAllowlist: ['ABOGADO', 'DEFENSA_PUBLICA', 'INTERPRETE'],
      ),
      SemanticZone(
        id: 'cantidad',
        label: 'Cuántos',
        hint: 'Cantidad',
        question: '¿Cuántos?',
        emoji: '🔢',
        semanticWeight: 0.25,
        optional: true,
        glossAllowlist: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
      ),
    ],
  ),

  SemanticContext(
    id: 'otro',
    name: 'Declarar como testigo',
    icon: 'visibility',
    emoji: '👁️',
    description: 'Presencié un robo, violencia o accidente',
    entryZoneId: 'que',
    baseUrgency: UrgencyLevel.medium,
    zones: const [
      SemanticZone(
        id: 'que',
        label: 'Hecho',
        hint: 'Qué presencié',
        question: '¿Qué hecho presenciaste?',
        emoji: '⚡',
        semanticWeight: 0.85,
        glossAllowlist: [
          'ROBAR', 'MALTRATAR', 'AMENAZAR', 'ABUSAR', 'VIOLACION',
          'DANAR', 'ACCIDENTE', 'DISCRIMINACION', 'VIOLENCIA',
        ],
        relatedZones: ['personas', 'victima', 'lugar'],
      ),
      SemanticZone(
        id: 'personas',
        label: 'Quién agredió',
        hint: 'Quién cometió el hecho',
        question: '¿Quién cometió el hecho?',
        emoji: '👤',
        semanticWeight: 0.7,
        maxPicks: 2,
        glossAllowlist: ['HOMBRE', 'MUJER', 'VECINO', 'MILITAR', 'SOLDADO'],
        relatedZones: ['victima', 'lugar'],
      ),
      SemanticZone(
        id: 'victima',
        label: 'A quién agredió',
        hint: 'Quién fue agredido',
        question: '¿A quién se lo hizo?',
        emoji: '🧑‍🤝‍🧑',
        semanticWeight: 0.6,
        optional: true,
        maxPicks: 2,
        glossAllowlist: ['HOMBRE', 'MUJER', 'FAMILIAR', 'PAREJA', 'VECINO'],
        leadGloss: kVictimMarker,
        relatedZones: ['lugar'],
      ),
      SemanticZone(
        id: 'vehiculo',
        label: 'Vehículo',
        hint: 'Qué vehículo vi',
        question: '¿Qué vehículo estuvo involucrado?',
        emoji: '🚗',
        semanticWeight: 0.55,
        optional: true,
        maxPicks: 2,
        glossAllowlist: [
          'AUTO', 'MOTOCICLETA', 'BICICLETA', 'MICRO', 'TAXI', 'TRUFI',
        ],
        leadGloss: kVehicleMarker,
        relatedZones: ['lugar'],
      ),
      SemanticZone(
        id: 'lugar',
        label: 'Lugar',
        hint: 'Dónde ocurrió',
        question: '¿Dónde ocurrió?',
        emoji: '📍',
        semanticWeight: 0.6,
        glossAllowlist: [
          'CALLE', 'AVENIDA', 'PLAZA', 'MERCADO',
          'PARADA', 'CASA', 'COCHABAMBA',
        ],
        relatedZones: ['tiempo'],
      ),
      SemanticZone(
        id: 'tiempo',
        label: 'Tiempo',
        hint: 'Cuándo',
        question: '¿Cuándo ocurrió?',
        emoji: '🕐',
        semanticWeight: 0.45,
        optional: true,
        glossAllowlist: [
          'AHORA', 'HOY', 'AYER', 'ANTEAYER',
          'MINUTO', 'HORA', 'DIA', 'SEMANA', 'MES',
        ],
        chainTriggers: ['MINUTO', 'HORA', 'DIA', 'SEMANA', 'MES'],
        chainZoneId: 'cantidad',
      ),
      SemanticZone(
        id: 'conocimiento',
        label: 'Conocimiento',
        hint: 'Si conozco a la persona involucrada',
        question: '¿Conoces a la persona?',
        emoji: '🤝',
        semanticWeight: 0.35,
        optional: true,
        glossAllowlist: ['CONOCER', 'DESCONOCER'],
      ),
      SemanticZone(
        id: 'apoyo_legal',
        label: 'Apoyo legal',
        hint: 'Si necesito abogado o intérprete',
        question: '¿Necesitas apoyo legal?',
        emoji: '⚖️',
        semanticWeight: 0.3,
        optional: true,
        maxPicks: 2,
        glossAllowlist: ['ABOGADO', 'DEFENSA_PUBLICA', 'INTERPRETE'],
      ),
      SemanticZone(
        id: 'cantidad',
        label: 'Cuántos',
        hint: 'Cantidad',
        question: '¿Cuántos?',
        emoji: '🔢',
        semanticWeight: 0.25,
        optional: true,
        glossAllowlist: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
      ),
    ],
  ),

  SemanticContext(
    id: 'tramite',
    name: 'Trámites',
    icon: 'app_registration',
    emoji: '📋',
    description: 'Presentar, pedir, corregir o recoger documentación',
    entryZoneId: 'accion',
    zones: const [
      SemanticZone(
        id: 'accion',
        label: 'Gestión',
        hint: 'Qué necesito hacer',
        question: '¿Qué necesitas hacer?',
        emoji: '📋',
        semanticWeight: 0.9,
        glossAllowlist: [
          'PRESENTAR', 'PEDIR', 'RECOGER', 'CORREGIR',
          'COPIAR', 'GESTIONAR', 'SEGUIMIENTO', 'MOSTRAR',
        ],
        relatedZones: ['documento', 'caso', 'donde'],
      ),
      SemanticZone(
        id: 'documento',
        label: 'Documento',
        hint: 'Qué documento oficial',
        question: '¿Qué documento?',
        emoji: '📄',
        semanticWeight: 0.85,
        maxPicks: 2,
        glossAllowlist: [
          'CARNET', 'PASAPORTE', 'LICENCIA_DECONDUCIR', 'CERTIFICADO',
          'CONSTANCIA', 'COMPROBANTE', 'FORMULARIO', 'MEMORIAL', 'TITULO',
        ],
        relatedZones: ['caso', 'donde'],
      ),
      SemanticZone(
        id: 'caso',
        label: 'Caso',
        hint: 'Número de caso o expediente al que corresponde',
        question: '¿Sobre qué caso?',
        emoji: '🧾',
        semanticWeight: 0.82,
        optional: true,
        glossAllowlist: [
          'CASO', 'EXPEDIENTE', 'CODIGO', 'NUREJ',
          'WEBID', 'JUICIO', 'AUDIENCIA', 'CITACION',
        ],
        relatedZones: ['donde'],
      ),
      SemanticZone(
        id: 'donde',
        label: 'Institución',
        hint: 'Ante qué institución',
        question: '¿Ante qué institución?',
        emoji: '🏛️',
        semanticWeight: 0.6,
        glossAllowlist: [
          'FISCALIA', 'FELCC', 'FELCV', 'JUZGADO',
          'DEFENSA_PUBLICA', 'SEPAV', 'TRIBUNAL', 'ORGANO_JUDICIAL',
          'OFICINA', 'VENTANILLA', 'DESPACHO',
        ],
        relatedZones: ['apoyo'],
      ),
      SemanticZone(
        id: 'observacion',
        label: 'Observación',
        hint: 'Qué me observaron',
        question: '¿Qué te observaron?',
        emoji: '⚠️',
        semanticWeight: 0.55,
        optional: true,
        glossAllowlist: ['OBSERVACION', 'REQUISITO', 'SUBSANACION', 'FORMATO', 'FALTA'],
      ),
      SemanticZone(
        id: 'plazo',
        label: 'Plazo',
        hint: 'Para cuándo lo necesito',
        question: '¿Para cuándo lo necesitas?',
        emoji: '🕐',
        semanticWeight: 0.4,
        optional: true,
        glossAllowlist: [
          'AHORA', 'HOY', 'MANANA', 'PASADO_MANANA', 'DIA', 'SEMANA', 'MES',
        ],
        chainTriggers: ['DIA', 'SEMANA', 'MES'],
        chainZoneId: 'cantidad',
      ),
      SemanticZone(
        id: 'cantidad',
        label: 'Cuántos',
        hint: 'Cantidad',
        question: '¿Cuántos?',
        emoji: '🔢',
        semanticWeight: 0.3,
        optional: true,
        glossAllowlist: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
      ),
      SemanticZone(
        id: 'apoyo',
        label: 'Apoyo',
        hint: 'Intérprete o abogado',
        question: '¿Necesitas apoyo?',
        emoji: '🤝',
        semanticWeight: 0.5,
        optional: true,
        glossAllowlist: ['INTERPRETE', 'ABOGADO', 'ACOMPANAR', 'ASISTENTE'],
      ),
      SemanticZone(
        id: 'quien',
        label: 'Para quién',
        hint: 'De quién es el trámite',
        question: '¿Para quién es el trámite?',
        emoji: '👤',
        semanticWeight: 0.4,
        optional: true,
        glossAllowlist: ['YO', 'FAMILIAR', 'PAREJA', 'HOMBRE', 'MUJER'],
      ),
      SemanticZone(
        id: 'perdida',
        label: 'Pérdida',
        hint: 'Qué perdí',
        question: '¿Qué perdiste?',
        emoji: '🔍',
        semanticWeight: 0.45,
        optional: true,
        glossAllowlist: [
          'PERDER', 'CARNET', 'PASAPORTE', 'LICENCIA_DECONDUCIR', 'TITULO',
          'CERTIFICADO', 'CONSTANCIA', 'TELEFONO', 'MOCHILA',
        ],
      ),
    ],
  ),

  SemanticContext(
    id: 'consulta',
    name: 'Consultas',
    icon: 'balance',
    emoji: '💬',
    description: 'Estado de un caso, orientación y derechos',
    entryZoneId: 'necesidad',
    zones: const [
      SemanticZone(
        id: 'necesidad',
        label: 'Necesidad',
        hint: 'Qué necesito saber',
        question: '¿Qué necesitas hacer?',
        emoji: '💬',
        semanticWeight: 0.9,
        glossAllowlist: [
          'SEGUIMIENTO', 'CASO', 'INTERPRETE', 'NO_SABER',
          'COMPRENDER', 'ACLARAR', 'AYUDAR', 'ATENDER',
        ],
        relatedZones: ['avance', 'materia', 'identificador', 'donde'],
      ),
      SemanticZone(
        id: 'avance',
        label: 'Avance',
        hint: 'Qué quiero saber de la investigación',
        question: '¿Qué necesita saber?',
        emoji: '🔎',
        semanticWeight: 0.88,
        optional: true,
        glossAllowlist: ['AVANCE', 'CASO', 'ESTADO', 'INVESTIGACION', 'AUDIENCIA'],
        relatedZones: ['defensa', 'identificador'],
      ),
      SemanticZone(
        id: 'defensa',
        label: 'Defensa',
        hint: 'Si tengo abogado',
        question: '¿Tiene abogado?',
        emoji: '⚖️',
        semanticWeight: 0.75,
        optional: true,
        glossAllowlist: ['SI', 'NO', 'DEFENSA_PUBLICA', 'ABOGADO'],
        relatedZones: ['identificador'],
      ),
      SemanticZone(
        id: 'materia',
        label: 'Materia',
        hint: 'Sobre qué consulto',
        question: '¿Sobre qué quieres consultar?',
        emoji: '🧾',
        semanticWeight: 0.85,
        glossAllowlist: [
          'CASO', 'EXPEDIENTE', 'ESTADO', 'TRAMITE',
          'REQUISITO', 'NOTIFICACION', 'CITACION', 'AUDIENCIA',
        ],
        relatedZones: ['identificador', 'donde'],
      ),
      SemanticZone(
        id: 'identificador',
        label: 'Número de caso',
        hint: 'NUREJ, WebID o código',
        question: '¿Tienes el número de tu caso?',
        emoji: '🔢',
        semanticWeight: 0.8,
        optional: true,
        glossAllowlist: [
          'CODIGO', 'NUREJ', 'WEBID', 'EXPEDIENTE', 'NO_SABER', 'NO_RECUERDO',
        ],
      ),
      SemanticZone(
        id: 'responsable',
        label: 'Responsable',
        hint: 'Quién lleva mi caso',
        question: '¿Quién lleva tu caso?',
        emoji: '👤',
        semanticWeight: 0.7,
        optional: true,
        glossAllowlist: ['FISCAL', 'JUEZ', 'ABOGADO', 'AUTORIDAD', 'COORDINADOR'],
      ),
      SemanticZone(
        id: 'donde',
        label: 'Dónde ir',
        hint: 'A qué institución u oficina acudo',
        question: '¿Dónde debes ir?',
        emoji: '🏛️',
        semanticWeight: 0.65,
        glossAllowlist: [
          'FISCALIA', 'FELCC', 'FELCV', 'JUZGADO',
          'DEFENSA_PUBLICA', 'SEPAV', 'TRIBUNAL', 'ORGANO_JUDICIAL',
          'OFICINA', 'VENTANILLA', 'DESPACHO', 'PISO',
        ],
      ),
      SemanticZone(
        id: 'documento',
        label: 'Documento',
        hint: 'Qué debo llevar',
        question: '¿Qué documento debes llevar?',
        emoji: '📄',
        semanticWeight: 0.6,
        optional: true,
        glossAllowlist: [
          'CARNET', 'PASAPORTE', 'CERTIFICADO', 'CONSTANCIA',
          'COMPROBANTE', 'FOTOCOPIA', 'NOTIFICACION',
        ],
      ),
      SemanticZone(
        id: 'apoyo',
        label: 'Apoyo',
        hint: 'Intérprete o abogado',
        question: '¿Necesitas apoyo?',
        emoji: '🤝',
        semanticWeight: 0.5,
        optional: true,
        glossAllowlist: ['INTERPRETE', 'ABOGADO', 'ACOMPANAR', 'AYUDAR'],
      ),
      SemanticZone(
        id: 'plazo',
        label: 'Cuándo volver',
        hint: 'Para cuándo',
        question: '¿Cuándo debes volver?',
        emoji: '🕐',
        semanticWeight: 0.4,
        optional: true,
        glossAllowlist: ['HOY', 'MANANA', 'PASADO_MANANA', 'DIA', 'SEMANA', 'MES'],
        chainTriggers: ['DIA', 'SEMANA', 'MES'],
        chainZoneId: 'cantidad',
      ),
      SemanticZone(
        id: 'cantidad',
        label: 'Cuántos',
        hint: 'Cantidad',
        question: '¿Cuántos?',
        emoji: '🔢',
        semanticWeight: 0.3,
        optional: true,
        glossAllowlist: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
      ),
    ],
  ),
];

const Map<String, List<String>> kContextCardSources = {
  'tramite': ['orientacion', 'tramite_id', 'perdida'],
  'consulta': ['orientacion', 'tramite_id'],
  'preguntas': ['preguntas', 'orientacion', 'tramite_id'],
};

class ContextFamily {
  final String id;
  final String name;
  final String emoji;
  final String description;
  final List<String> contextIds;

  const ContextFamily({
    required this.id,
    required this.name,
    required this.emoji,
    required this.description,
    required this.contextIds,
  });
}

const List<ContextFamily> contextFamilies = [
  ContextFamily(
    id: 'identificacion',
    name: 'Mis datos',
    emoji: '🪪',
    description: 'Nombre, edad y documento',
    contextIds: ['identificacion'],
  ),
  ContextFamily(
    id: 'denuncias',
    name: 'Denuncias',
    emoji: '🚨',
    description: 'Robo, violencia, accidente o declarar como testigo',
    contextIds: ['denuncia_robo', 'violencia', 'accidente', 'otro'],
  ),
  ContextFamily(
    id: 'consultas',
    name: 'Consultas',
    emoji: '💬',
    description: 'Estado de un caso, orientación y derechos',
    contextIds: ['consulta'],
  ),
  ContextFamily(
    id: 'tramites',
    name: 'Trámites',
    emoji: '📋',
    description: 'Documentos, certificados, pérdidas y antecedentes',
    contextIds: ['tramite'],
  ),
  ContextFamily(
    id: 'preguntas',
    name: 'Preguntas',
    emoji: '❓',
    description: 'Quiero preguntar algo',
    contextIds: ['preguntas'],
  ),
];

List<SemanticContext> get allSelectableContexts =>
    [...availableContexts, preguntasContext, identificacionContext];

List<SemanticContext> contextsOfFamily(ContextFamily family) => [
      for (final id in family.contextIds)
        for (final ctx in allSelectableContexts)
          if (ctx.id == id) ctx,
    ];

List<String> cardSourceContexts(String contextId) {
  final heredados = kContextCardSources[contextId];
  if (heredados == null) return [contextId];
  return [contextId, ...heredados];
}

String resolveAssemblerContext(
  String contextId,
  List<String> glosses,
  String? Function(String gloss) cardCategoryOf,
) {
  if (contextId == 'preguntas') return 'preguntas';
  if (contextId == 'identificacion') return 'identificacion';

  if (contextId == 'consulta') return 'orientacion';

  if (contextId != 'tramite') return contextId;
  var hasObject = false;
  var hasDocOrProcedure = false;
  for (final g in glosses) {
    if (g.toUpperCase() == 'PERDER') hasObject = true;
    final cat = cardCategoryOf(g);
    if (cat == 'Objetos') hasObject = true;
    if (cat == 'Documentos' || cat == 'Conceptos jurídicos') hasDocOrProcedure = true;
  }
  final dijoPerder = glosses.any((g) => g.toUpperCase() == 'PERDER');
  if (dijoPerder || (hasObject && !hasDocOrProcedure)) return 'perdida';
  if (hasDocOrProcedure) return 'tramite_id';
  return 'orientacion';
}

SemanticContext? contextById(String id) {
  for (final context in allSelectableContexts) {
    if (context.id == id) return context;
  }
  return null;
}
