part of 'local_sentence_assembler.dart';

// Léxico español del ensamblador: el papel semántico de cada glosa y su
// forma en español. Es datos; la composición vive en
// local_sentence_assembler.dart.

/// Glosa → papel semántico y forma en español.
const Map<String, _Lex> _lexicon = {
  '0': _Lex(_Role.verboAccion, '0'),
  '1': _Lex(_Role.verboAccion, '1'),
  '2': _Lex(_Role.verboAccion, '2'),
  '3': _Lex(_Role.verboAccion, '3'),
  '4': _Lex(_Role.verboAccion, '4'),
  '5': _Lex(_Role.verboAccion, '5'),
  '6': _Lex(_Role.verboAccion, '6'),
  '7': _Lex(_Role.verboAccion, '7'),
  '8': _Lex(_Role.verboAccion, '8'),
  '9': _Lex(_Role.verboAccion, '9'),
  'A': _Lex(_Role.verboAccion, 'a'),
  'ABOGADO': _Lex(_Role.servicio, 'un abogado'),
  'ABRIR': _Lex(_Role.verboAccion, 'abrí'),
  'ABUSAR': _Lex(_Role.verboAgresion, 'cometió abusos'),
  'ACEPTAR': _Lex(_Role.verboAccion, 'acepto'),
  'ACOMPAÑAR': _Lex(_Role.verboAccion, 'acompañar'),
  'ADULTO': _Lex(_Role.personaDesc, 'adulto'),
  'AHORA': _Lex(_Role.tiempo, 'ahora mismo'),
  'ALCALDIA': _Lex(_Role.institucion, 'en la alcaldía'),
  'ALLA': _Lex(_Role.lugar, 'allá'),
  'ALLI': _Lex(_Role.lugar, 'allí'),
  'ALTO': _Lex(_Role.rasgo, 'alto'),
  'AL_LADO': _Lex(_Role.lugar, 'al lado'),
  'AMBOS': _Lex(_Role.sujeto, 'ambos'),
  'AMENAZAR': _Lex(_Role.verboAgresion, 'amenazó'),
  'AMIGO': _Lex(_Role.personaDesc, 'un amigo'),
  'ANDAR': _Lex(_Role.verboAccion, 'caminaba'),
  'ANTEAYER': _Lex(_Role.tiempo, 'anteayer'),
  'AQUI': _Lex(_Role.lugar, 'aquí'),
  'ARREGLAR': _Lex(_Role.verboAccion, 'quiero corregir'),
  'ARRESTAR': _Lex(_Role.verboAccion, 'arrestaron'),
  'ASISTENCIA': _Lex(_Role.documento, 'asistencia'),
  'ASISTENTE': _Lex(_Role.servicio, 'un asistente'),
  'ASOCIACION_SORDOS': _Lex(_Role.personaDesc, 'la asociación de sordos'),
  'ATENDER': _Lex(_Role.verboAccion, 'atender'),
  'ATRAS': _Lex(_Role.lugar, 'atrás'),
  'AUMENTAR': _Lex(_Role.verboAccion, 'quiero agregar información'),
  'AUTORIDAD': _Lex(_Role.institucion, 'la autoridad'),
  'AUXILIO': _Lex(_Role.urgencia, 'auxilio urgente'),
  'AVENIDA': _Lex(_Role.lugar, 'en la avenida'),
  'AVISAR': _Lex(_Role.verboAccion, 'avisar'),
  'AYER': _Lex(_Role.tiempo, 'ayer'),
  'AYUDAR': _Lex(_Role.verboAccion, 'necesito ayuda'),
  'AZUL': _Lex(_Role.descriptor, 'de color azul'),
  'AÑO': _Lex(_Role.tiempo, 'año'),
  'AÑO_PASADO': _Lex(_Role.tiempo, 'el año pasado'),
  'AUN': _Lex(_Role.tiempo, 'aún'),
  'B': _Lex(_Role.verboAccion, 'b'),
  'BAJO': _Lex(_Role.rasgo, 'bajo'),
  'BANCO': _Lex(_Role.lugar, 'en el banco'),
  'BARRIO': _Lex(_Role.lugar, 'en el barrio'),
  'BILLETES': _Lex(_Role.objeto, 'billetes y dinero'),
  'BOCA': _Lex(_Role.objeto, 'la boca'),
  'BOLSA': _Lex(_Role.objeto, 'mi bolsa'),
  'BRAZO': _Lex(_Role.objeto, 'el brazo'),
  'BUENO': _Lex(_Role.descriptor, 'bueno'),
  'BUENOS_DIAS': _Lex(_Role.marcador, 'buenos días'),
  'BURLAR': _Lex(_Role.verboAccion, 'se burlaron'),
  'BUSCAR': _Lex(_Role.verboAccion, 'quiero buscar'),
  'C': _Lex(_Role.verboAccion, 'c'),
  'CABELLO': _Lex(_Role.objeto, 'el cabello'),
  'CADA_DIA': _Lex(_Role.tiempo, 'cada día'),
  'CAJA': _Lex(_Role.objeto, 'la caja'),
  'CALLE': _Lex(_Role.lugar, 'en la calle'),
  'CAMBIAR': _Lex(_Role.verboAccion, 'cambié'),
  'CARO': _Lex(_Role.descriptor, 'costoso'),
  'CARPETA': _Lex(_Role.documento, 'la carpeta de documentos'),
  'CASA': _Lex(_Role.lugar, 'en mi casa'),
  'CELULAR': _Lex(_Role.objeto, 'mi celular'),
  // Sin "del lugar": esa relación necesita su referencia real (auditoría
  // 2026-09); un valor fijo fabricaba una referencia vaga cuando no se
  // preguntó cerca de qué.
  'CERCA': _Lex(_Role.lugar, 'cerca'),
  'CERTIFICADO': _Lex(_Role.documento, 'un certificado'),
  'CHAMARRA': _Lex(_Role.objeto, 'mi chamarra'),
  'COCHABAMBA': _Lex(_Role.lugar, 'en Cochabamba'),
  'COMPAÑERO': _Lex(_Role.personaDesc, 'un compañero'),
  'COMPRAR': _Lex(_Role.verboAccion, 'compré'),
  'COMPRENDER': _Lex(_Role.marcador, 'comprender'),
  'COMPUTADORA': _Lex(_Role.objeto, 'una computadora'),
  'COMUNIDAD_SORDA': _Lex(_Role.personaDesc, 'la comunidad sorda'),
  'CONFIANZA': _Lex(_Role.emocion, 'tengo confianza'),
  // "Conozco" solo no dice a quién: el corpus penal judicial §4 pregunta
  // "¿conoce a la persona?" y la respuesta debe nombrar el complemento,
  // sí o no ("Sí/No conozco a esa persona"), no quedar en un verbo suelto.
  'CONOCER': _Lex(_Role.verboAccion, 'conozco a esa persona'),
  'CONTESTAR_DOS_VECES': _Lex(_Role.verboAccion, 'contesté dos veces'),
  'CONTINUAR': _Lex(_Role.verboAccion, 'continúa'),
  'CONVOCAR': _Lex(_Role.tramite, 'una citación'),
  'CORTO': _Lex(_Role.descriptor, 'corto'),
  'CREER': _Lex(_Role.verboAccion, 'creo'),
  'CURAR': _Lex(_Role.verboAccion, 'curar'),
  'CUAL': _Lex(_Role.interrogativa, 'cuál'),
  'CUANDO': _Lex(_Role.interrogativa, 'cuándo'),
  'CUANTOS': _Lex(_Role.interrogativa, 'cuántos'),
  'CAMARA_FOTOGRAFICA': _Lex(_Role.objeto, 'una cámara fotográfica'),
  'COMO': _Lex(_Role.interrogativa, 'cómo'),
  'D': _Lex(_Role.verboAccion, 'd'),
  'DAR': _Lex(_Role.verboAccion, 'entregué'),
  'DAÑAR': _Lex(_Role.verboAgresion, 'dañó'),
  'DECIDIR': _Lex(_Role.verboAccion, 'decidí'),
  'DEJAR': _Lex(_Role.verboAccion, 'dejé'),
  'DELGADO': _Lex(_Role.rasgo, 'delgado'),
  'DENTRO': _Lex(_Role.lugar, 'dentro'),
  'DESCANSO': _Lex(_Role.tiempo, 'en horario de descanso'),
  'DESPUES': _Lex(_Role.tiempo, 'después'),
  'DEVOLVER': _Lex(_Role.verboAccion, 'quiero que devuelvan'),
  'DE_NADA': _Lex(_Role.marcador, 'de nada'),
  'DIBUJAR': _Lex(_Role.verboAccion, 'dibujé'),
  'DIFERENTE': _Lex(_Role.descriptor, 'diferente'),
  'DIFICIL': _Lex(_Role.descriptor, 'difícil'),
  'DINERO': _Lex(_Role.objeto, 'mi dinero'),
  'DIRECCION': _Lex(_Role.lugar, 'en mi dirección'),
  'DISCRIMINACION': _Lex(_Role.documento, 'discriminación'),
  'DOCTOR': _Lex(_Role.servicio, 'un doctor'),
  'DOLOR': _Lex(_Role.urgencia, 'dolor físico'),
  'DORMIR': _Lex(_Role.verboAccion, 'dormía'),
  'DURANTE': _Lex(_Role.tiempo, 'durante ese tiempo'),
  'DIA': _Lex(_Role.tiempo, 'día'),
  'DONDE': _Lex(_Role.interrogativa, 'dónde'),
  'E': _Lex(_Role.verboAccion, 'e'),
  'EDAD': _Lex(_Role.marcador, 'tengo esa edad'),
  'ELLA': _Lex(_Role.sujeto, 'ella'),
  'ELLOS': _Lex(_Role.sujeto, 'ellos'),
  'EMPEZAR': _Lex(_Role.verboAccion, 'empezó'),
  'ENCONTRARSE': _Lex(_Role.verboAccion, 'me encontré'),
  'ENFRENTE': _Lex(_Role.lugar, 'enfrente'),
  'ENGAÑAR': _Lex(_Role.verboAgresion, 'engañó y estafó'),
  'ENVIAR': _Lex(_Role.verboAccion, 'envié'),
  'ESCAPAR': _Lex(_Role.verboAgresion, 'escapó'),
  'ESCONDER': _Lex(_Role.verboAccion, 'escondió'),
  'ESCRIBIR': _Lex(_Role.verboAccion, 'quiero escribir'),
  'ESCUELA': _Lex(_Role.lugar, 'en la escuela'),
  'ESCUELA_NOCTURNA': _Lex(_Role.lugar, 'en la escuela nocturna'),
  'ESPERAR': _Lex(_Role.verboAccion, 'esperar'),
  'ESPOSA': _Lex(_Role.personaDesc, 'mi esposa'),
  'ESTAR_DE_ACUERDO': _Lex(_Role.marcador, 'estoy de acuerdo'),
  'EVALUAR': _Lex(_Role.verboAccion, 'evaluar'),
  'EXPLICAR': _Lex(_Role.verboAccion, 'quiero explicar'),
  'F': _Lex(_Role.verboAccion, 'f'),
  'FACTURA': _Lex(_Role.documento, 'la factura'),
  // verboAccion, no verboAgresion: perder algo no es una agresión de un
  // tercero. Con verboAgresion, "FALTA CELULAR" se redactaba "una persona
  // me perdí mi celular" (auditoría 2026-09, hallazgo PERDER).
  'FALTA': _Lex(_Role.verboAccion, 'perdí'),
  'FECHA': _Lex(_Role.tiempo, 'en la fecha indicada'),
  'FELCC': _Lex(_Role.institucion, 'en la FELCC'),
  'FELCV': _Lex(_Role.institucion, 'en la FELCV'),
  'FILMAR': _Lex(_Role.verboAccion, 'filmé'),
  'FISCALIA': _Lex(_Role.institucion, 'en la Fiscalía'),
  'FLACO': _Lex(_Role.rasgo, 'delgado'),
  'FOTOCOPIA': _Lex(_Role.documento, 'una fotocopia'),
  'FOTOS': _Lex(_Role.objeto, 'fotografías'),
  'FRACTURA': _Lex(_Role.urgencia, 'una fractura'),
  'FUERA': _Lex(_Role.lugar, 'fuera'),
  'FUNCIONAR': _Lex(_Role.verboAccion, 'funciona'),
  'FUTURO': _Lex(_Role.tiempo, 'en el futuro'),
  'G': _Lex(_Role.verboAccion, 'g'),
  'GANAR_DINERO': _Lex(_Role.verboAccion, 'gané dinero'),
  'GESTIONAR': _Lex(_Role.verboAccion, 'quiero gestionar'),
  'GOBIERNO': _Lex(_Role.institucion, 'el gobierno'),
  'GORDO': _Lex(_Role.rasgo, 'de contextura gruesa'),
  'GORRA': _Lex(_Role.objeto, 'mi gorra'),
  'GRACIAS': _Lex(_Role.marcador, 'muchas gracias'),
  'GRATIS': _Lex(_Role.descriptor, 'gratuito'),
  'GRITAR': _Lex(_Role.verboAccion, 'gritó'),
  'GRUESO': _Lex(_Role.rasgo, 'grueso'),
  'GUARDAR': _Lex(_Role.verboAccion, 'guardé'),
  'H': _Lex(_Role.verboAccion, 'h'),
  'HABLAR': _Lex(_Role.verboAccion, 'quiero hablar'),
  'HACER': _Lex(_Role.verboAccion, 'hice'),
  'HASTA_LUEGO': _Lex(_Role.marcador, 'hasta luego'),
  'HASTA_MAÑANA': _Lex(_Role.marcador, 'hasta mañana'),
  'HERIDA': _Lex(_Role.urgencia, 'una herida'),
  'HERMANA': _Lex(_Role.personaDesc, 'mi hermana'),
  'HERMANO': _Lex(_Role.personaDesc, 'mi hermano'),
  'HIJA': _Lex(_Role.personaDesc, 'mi hija'),
  'HIJO': _Lex(_Role.personaDesc, 'mi hijo'),
  'HOLA': _Lex(_Role.marcador, 'hola'),
  'HOMBRE': _Lex(_Role.personaDesc, 'un hombre'),
  'HORA': _Lex(_Role.tiempo, 'hora'),
  'HOSPITAL': _Lex(_Role.institucion, 'en el hospital'),
  'HOY': _Lex(_Role.tiempo, 'hoy'),
  'HUESOS': _Lex(_Role.urgencia, 'los huesos'),
  'I': _Lex(_Role.verboAccion, 'i'),
  'IDENTIDAD': _Lex(_Role.marcador, 'mi carnet de identidad'),
  'IDENTIFICAR': _Lex(_Role.verboAccion, 'puedo identificar'),
  'IGNORAR': _Lex(_Role.verboAccion, 'me ignoraron'),
  'INSTITUCION': _Lex(_Role.institucion, 'en la institución'),
  'INTERNET': _Lex(_Role.objeto, 'por internet'),
  'INTERPRETE': _Lex(_Role.servicio, 'un intérprete de LSB'),
  'INVESTIGACION': _Lex(_Role.tramite, 'la investigación de mi caso'),
  'IR': _Lex(_Role.verboAccion, 'fui'),
  'J': _Lex(_Role.verboAccion, 'j'),
  'JAMAS': _Lex(_Role.tiempo, 'jamás'),
  'JEFE': _Lex(_Role.personaDesc, 'mi jefe'),
  'JOVEN': _Lex(_Role.personaDesc, 'joven'),
  'JUEVES': _Lex(_Role.tiempo, 'el jueves'),
  'JUEZ': _Lex(_Role.institucion, 'el juez'),
  'JULIO': _Lex(_Role.tiempo, 'en julio'),
  'JUSTICIA': _Lex(_Role.documento, 'la justicia'),
  'JUZGADO': _Lex(_Role.institucion, 'en el juzgado'),
  'K': _Lex(_Role.verboAccion, 'k'),
  'L': _Lex(_Role.verboAccion, 'l'),
  'LADRON': _Lex(_Role.personaDesc, 'un ladrón'),
  'LEER': _Lex(_Role.verboAccion, 'quiero leer'),
  'LEJOS': _Lex(_Role.lugar, 'lejos'),
  'LENTES': _Lex(_Role.objeto, 'mis lentes'),
  'LENTO': _Lex(_Role.descriptor, 'despacio'),
  'LEY': _Lex(_Role.documento, 'la ley'),
  'LIBRE': _Lex(_Role.tiempo, 'libre'),
  'LISTA': _Lex(_Role.documento, 'la lista'),
  'LLAMAR': _Lex(_Role.verboAccion, 'llamé'),
  'LLEGAR': _Lex(_Role.verboAccion, 'llegué'),
  'LLEVAR': _Lex(_Role.verboAccion, 'llevaba'),
  'LO_SIENTO': _Lex(_Role.marcador, 'lo siento'),
  'LUEGO': _Lex(_Role.tiempo, 'luego'),
  'LUNES': _Lex(_Role.tiempo, 'el lunes'),
  'M': _Lex(_Role.verboAccion, 'm'),
  'MAL': _Lex(_Role.descriptor, 'mal'),
  'MALTRATAR': _Lex(_Role.verboAgresion, 'maltrató'),
  'MAMA': _Lex(_Role.personaDesc, 'mi mamá'),
  'MARTES': _Lex(_Role.tiempo, 'el martes'),
  'MARZO': _Lex(_Role.tiempo, 'en marzo'),
  'MAÑANA': _Lex(_Role.tiempo, 'mañana'),
  'MEDICINA': _Lex(_Role.objeto, 'medicinas'),
  'MEJOR': _Lex(_Role.descriptor, 'mejor'),
  'MENTIRA': _Lex(_Role.marcador, 'es mentira'),
  'MERCADO': _Lex(_Role.lugar, 'en el mercado'),
  'MES': _Lex(_Role.tiempo, 'mes'),
  'MICRO': _Lex(_Role.objeto, 'un micro'),
  'MIEDO': _Lex(_Role.emocion, 'tengo miedo'),
  'MILITAR': _Lex(_Role.personaDesc, 'un militar'),
  'MINUTO': _Lex(_Role.tiempo, 'minuto'),
  'MIRAR': _Lex(_Role.verboAccion, 'vi'),
  'MOCHILA': _Lex(_Role.objeto, 'mi mochila'),
  'MOMENTO': _Lex(_Role.tiempo, 'en ese momento'),
  'MOSTRAR': _Lex(_Role.verboAccion, 'puedo mostrar'),
  'MUCHO': _Lex(_Role.descriptor, 'mucho'),
  'MUJER': _Lex(_Role.personaDesc, 'una mujer'),
  'MAS_O_MENOS': _Lex(_Role.marcador, 'más o menos'),
  'MIO': _Lex(_Role.sujeto, 'mi'),
  'N': _Lex(_Role.verboAccion, 'n'),
  'NARRAR': _Lex(_Role.verboAccion, 'quiero relatar'),
  'NECESITAR': _Lex(_Role.verboAccion, 'necesitar'),
  'NEGRO': _Lex(_Role.descriptor, 'de color negro'),
  'NO': _Lex(_Role.marcador, 'no'),
  'NOMBRE': _Lex(_Role.marcador, 'mi nombre es'),
  'NOSOTROS': _Lex(_Role.sujeto, 'nosotros'),
  'NO_ESTAR_DE_ACUERDO': _Lex(_Role.marcador, 'no estoy de acuerdo'),
  'NO_PUEDO': _Lex(_Role.marcador, 'no puedo'),
  'NO_SABER': _Lex(_Role.marcador, 'no sé'),
  'NUEVO': _Lex(_Role.descriptor, 'nuevo'),
  'O': _Lex(_Role.verboAccion, 'o'),
  'OBSERVAR': _Lex(_Role.verboAccion, 'observé'),
  'OCUPADO': _Lex(_Role.tiempo, 'ocupado'),
  'OFICIAL': _Lex(_Role.servicio, 'un oficial'),
  'OFICINA': _Lex(_Role.lugar, 'en la oficina'),
  'ORGANIZAR': _Lex(_Role.verboAccion, 'organicé'),
  'OSCURO': _Lex(_Role.descriptor, 'oscuro'),
  'OYENTE': _Lex(_Role.personaDesc, 'oyente'),
  'OIR': _Lex(_Role.verboAccion, 'escuché'),
  'P': _Lex(_Role.verboAccion, 'p'),
  'PALABRA': _Lex(_Role.verboAccion, 'palabra'),
  'PANTALON': _Lex(_Role.objeto, 'mi pantalón'),
  'PAPEL': _Lex(_Role.documento, 'el documento'),
  'PAREJA': _Lex(_Role.personaDesc, 'mi pareja'),
  'PARIENTE': _Lex(_Role.personaDesc, 'un pariente'),
  'PASADO': _Lex(_Role.tiempo, 'en el pasado'),
  'PASADO_MAÑANA': _Lex(_Role.tiempo, 'pasado mañana'),
  'PASAPORTE': _Lex(_Role.documento, 'mi pasaporte'),
  'PEDIR': _Lex(_Role.verboAccion, 'solicito'),
  'PEGAR': _Lex(_Role.verboAgresion, 'golpeó y pegó'),
  'PELEAR': _Lex(_Role.verboAgresion, 'inició una pelea'),
  // verboAccion, no verboAgresion (auditoría 2026-09, hallazgo PERDER): ver
  // la nota en 'FALTA', misma causa.
  'PERDER': _Lex(_Role.verboAccion, 'perdí'),
  'PERMISO': _Lex(_Role.marcador, 'con permiso'),
  'PLAZA': _Lex(_Role.lugar, 'en la plaza'),
  'PLAZO': _Lex(_Role.tramite, 'el plazo'),
  'POCO': _Lex(_Role.descriptor, 'poco'),
  'POLERA': _Lex(_Role.objeto, 'mi polera'),
  'POLICIA': _Lex(_Role.institucion, 'en la policía'),
  'POR_FAVOR': _Lex(_Role.marcador, 'por favor'),
  'POSTERGAR': _Lex(_Role.tiempo, 'postergar'),
  'PREOCUPAR': _Lex(_Role.emocion, 'estoy preocupado'),
  'PRESENTAR': _Lex(_Role.verboAccion, 'quiero presentar'),
  'PRIMERA_VEZ': _Lex(_Role.tiempo, 'la primera vez'),
  'PROHIBIDO': _Lex(_Role.documento, 'prohibido'),
  'PROTEGER': _Lex(_Role.verboAccion, 'necesito protección'),
  'PROVINCIA': _Lex(_Role.lugar, 'en la provincia'),
  'PROXIMO': _Lex(_Role.tiempo, 'el próximo'),
  'PUEDO': _Lex(_Role.marcador, 'puedo'),
  'PUERTA': _Lex(_Role.objeto, 'la puerta'),
  'PAGINA': _Lex(_Role.documento, 'la página'),
  'Q': _Lex(_Role.verboAccion, 'q'),
  'QUEJAR': _Lex(_Role.verboAccion, 'quejar'),
  'QUERER': _Lex(_Role.verboAccion, 'querer'),
  'QUIEN': _Lex(_Role.interrogativa, 'quién'),
  'QUE': _Lex(_Role.interrogativa, 'qué'),
  'R': _Lex(_Role.verboAccion, 'r'),
  'RAYOS_X': _Lex(_Role.objeto, 'placas de rayos X'),
  'RECHAZAR': _Lex(_Role.verboAccion, 'rechazo'),
  'RECIBIR': _Lex(_Role.verboAccion, 'recibí'),
  'RECORDAR': _Lex(_Role.verboAccion, 'recuerdo'),
  'RESOLUCION': _Lex(_Role.documento, 'una resolución'),
  'RESULTADO': _Lex(_Role.documento, 'el resultado'),
  'REUNION': _Lex(_Role.verboAccion, 'reunión'),
  'ROBAR': _Lex(_Role.verboAgresion, 'robó'),
  'ROJO': _Lex(_Role.descriptor, 'de color rojo'),
  'S': _Lex(_Role.verboAccion, 's'),
  'SABER': _Lex(_Role.marcador, 'sé'),
  'SEGUNDO': _Lex(_Role.tiempo, 'segundo'),
  'SELLO': _Lex(_Role.documento, 'un sello oficial'),
  'SEMANA': _Lex(_Role.tiempo, 'semana'),
  'SEPARADOS': _Lex(_Role.personaDesc, 'separados'),
  'SEPDAVI': _Lex(_Role.institucion, 'en el SEPDAVI'),
  'SEPDEP': _Lex(_Role.institucion, 'en el SEPDEP'),
  'SEÑOR': _Lex(_Role.personaDesc, 'el señor'),
  'SIEMPRE': _Lex(_Role.tiempo, 'siempre'),
  'SOLUCIONAR': _Lex(_Role.verboAccion, 'quiero solucionar'),
  'SOPORTE': _Lex(_Role.documento, 'soporte'),
  'SORDO': _Lex(_Role.personaDesc, 'una persona sorda'),
  'SUYO': _Lex(_Role.sujeto, 'suyo'),
  'SABADO': _Lex(_Role.tiempo, 'el sábado'),
  'SI': _Lex(_Role.marcador, 'sí'),
  'T': _Lex(_Role.verboAccion, 't'),
  'TAL_VEZ': _Lex(_Role.marcador, 'tal vez'),
  'TARDE': _Lex(_Role.tiempo, 'por la tarde'),
  'TELEFONO': _Lex(_Role.objeto, 'mi teléfono'),
  'TEMOR': _Lex(_Role.emocion, 'tengo temor'),
  'TEMPRANO': _Lex(_Role.tiempo, 'temprano'),
  'TENER': _Lex(_Role.verboAccion, 'tener'),
  'TERMINAR': _Lex(_Role.verboAccion, 'terminó'),
  'TESTIGO': _Lex(_Role.testigo, 'un testigo'),
  'TESTIMONIO': _Lex(_Role.documento, 'mi testimonio'),
  'TIENDA': _Lex(_Role.lugar, 'en la tienda'),
  'TODOS_LOS_DIAS': _Lex(_Role.tiempo, 'todos los días'),
  'TOTAL': _Lex(_Role.verboAccion, 'total'),
  'TRABAJADOR': _Lex(_Role.personaDesc, 'un trabajador'),
  'TRAER': _Lex(_Role.verboAccion, 'puedo traer'),
  'TRISTE': _Lex(_Role.emocion, 'estoy triste'),
  'TRUFI': _Lex(_Role.objeto, 'un trufi'),
  'TRAMITE': _Lex(_Role.tramite, 'un trámite'),
  'TUYO': _Lex(_Role.sujeto, 'su'),
  'TU': _Lex(_Role.sujeto, 'tú'),
  'U': _Lex(_Role.verboAccion, 'u'),
  'URGENTE': _Lex(_Role.urgencia, 'de manera urgente'),
  'V': _Lex(_Role.verboAccion, 'v'),
  'VARIOS': _Lex(_Role.sujeto, 'varios'),
  'VECINO': _Lex(_Role.personaDesc, 'un vecino'),
  'VENDER': _Lex(_Role.verboAccion, 'vendí'),
  'VENIR': _Lex(_Role.verboAccion, 'vine'),
  'VER': _Lex(_Role.verboAccion, 'vi'),
  'VERDAD': _Lex(_Role.marcador, 'es verdad'),
  'VIDEO': _Lex(_Role.objeto, 'un video'),
  'VIERNES': _Lex(_Role.tiempo, 'el viernes'),
  'VIOLENCIA': _Lex(_Role.urgencia, 'un hecho de violencia'),
  'VIVIR': _Lex(_Role.verboAccion, 'vivo'),
  'VOLVER': _Lex(_Role.verboAccion, 'debo volver'),
  'W': _Lex(_Role.verboAccion, 'w'),
  'X': _Lex(_Role.verboAccion, 'x'),
  'Y': _Lex(_Role.verboAccion, 'y'),
  'YO': _Lex(_Role.sujeto, 'yo'),
  'Z': _Lex(_Role.verboAccion, 'z'),
  'EL': _Lex(_Role.sujeto, 'él'),
  'Ñ': _Lex(_Role.verboAccion, 'ñ'),
  'ORGANO_JUDICIAL': _Lex(_Role.institucion, 'en el Órgano Judicial'),
  'ULTIMO': _Lex(_Role.tiempo, 'el último'),

  // Vocabulario del corpus ausente del lexicón (auditoría 2026-09): estas
  // glosas se usan en aws/tests/casos_corpus.json pero nunca se agregaron
  // aquí, así que caían en la red de seguridad genérica en vez de
  // redactarse con su propio sentido. Se agregan en paridad con
  // GLOSS_LEXICON en aws/lambda_function.py.
  'AUDIENCIA': _Lex(_Role.tramite, 'una audiencia'),
  'CENTRO_DE_SALUD': _Lex(_Role.lugar, 'en el centro de salud'),
  'CONSTANCIA': _Lex(_Role.documento, 'una constancia'),
  'COPIAR': _Lex(_Role.verboAccion, 'copié'),
  'DEFENSA_PUBLICA': _Lex(_Role.institucion, 'en la Defensa Pública'),
  'ESTADO': _Lex(_Role.tramite, 'el estado'),
  'EXPAREJA': _Lex(_Role.personaDesc, 'mi expareja'),
  'EXPEDIENTE': _Lex(_Role.documento, 'el expediente'),
  'FORMULARIO': _Lex(_Role.documento, 'un formulario'),
  'FOTOGRAFIA': _Lex(_Role.objeto, 'una fotografía'),
  'MEMORIAL': _Lex(_Role.documento, 'un memorial'),
  'NOTIFICACION': _Lex(_Role.documento, 'la notificación'),
  'NO_ENTIENDO': _Lex(_Role.marcador, 'no entiendo'),
  'NO_RECUERDO': _Lex(_Role.marcador, 'no recuerdo'),
  'NUREJ': _Lex(_Role.documento, 'el NUREJ'),
  'OBSERVACION': _Lex(_Role.documento, 'una observación'),
  // "Un lugar seguro" no es dónde ocurrió el hecho: es la seguridad ACTUAL
  // de quien declara. Como _Role.lugar se fundía con el lugar del hecho
  // ("en mi casa y un lugar seguro"); como estado emocional se une a MIEDO
  // en su propia cláusula ("Tengo miedo y me encuentro en un lugar
  // seguro"), igual que el resto de _Role.emocion (auditoría 2026-09,
  // hallazgo CP-004).
  'SEGURO': _Lex(_Role.emocion, 'me encuentro en un lugar seguro'),
  // Sus hermanas de estado emocional (CONFIANZA, MIEDO, TEMOR...) son
  // _Role.emocion con una cláusula completa en primera persona; SOSPECHA
  // había quedado como _Role.motivo con una locución suelta ("por
  // sospecha"), que en denuncia_robo/violencia ningún compositor consume
  // y termina cayendo a la red de seguridad como "(por sospecha)" en vez
  // de una oración propia (auditoría 2026-09, hallazgo CP-010).
  'SOSPECHA': _Lex(_Role.emocion, 'tengo una sospecha'),
  'VENTANILLA': _Lex(_Role.lugar, 'en la ventanilla'),
  // Ya trae la preposición: `_joinConCanales` la reconoce como canal (por
  // WhatsApp), igual que ENGANAR+WHATSAPP.
  'WHATSAPP': _Lex(_Role.objeto, 'por WhatsApp'),

  // Narrativa de estafa sin verbo de agresión ("pagué y no me entregaron
  // el producto"): PAGAR/ENTREGAR/PRODUCTO faltaban por completo, así que
  // caían en la red de seguridad genérica ("Me sustrajeron...") y
  // calificaban el hecho como robo aunque la persona nunca lo dijo
  // (auditoría 2026-09, hallazgo "lagunas cerradas"). ENTREGAR se redacta
  // en la voz que recibe ("me entregaron") porque así compone con NO
  // ("no me entregaron") sin hornear la negación en el lexema.
  'PAGAR': _Lex(_Role.verboAccion, 'pagué'),
  'ENTREGAR': _Lex(_Role.verboAccion, 'me entregaron'),
  'PRODUCTO': _Lex(_Role.objeto, 'el producto'),

  // CORRER faltaba del lexicón: al no reconocerse, `_extractDetails` la
  // confundía con un nombre propio deletreado y la fundía en el lugar
  // ("en el mercado correr") en vez de cerrar el relato como huida
  // (auditoría 2026-09, hallazgo CP-002). Se trata igual que ESCAPAR.
  'CORRER': _Lex(_Role.verboAgresion, 'salió corriendo'),
  'BILLETERA': _Lex(_Role.objeto, 'mi billetera'),
  'PARADA': _Lex(_Role.lugar, 'en la parada'),

  // AUTO/MOTOCICLETA/TAXI/BICICLETA estaban en `_admiteDetalle` (admiten
  // placa) pero nunca se agregaron al lexicón: sin entrada, `_classify`
  // las trataba como token desconocido, y como su placa ya había quedado
  // registrada en `detalles` (por `_extractDetails`), `_ensureCoverage`
  // las daba por "consumidas" y ni siquiera aparecían en la red de
  // seguridad "(...)" — el vehículo y su placa desaparecían del todo de
  // la declaración (auditoría 2026-09, hallazgo "placa alfanumérica").
  // AUTO/MOTOCICLETA/BICICLETA son vehículos propios (blanco de ROBAR o
  // DAÑAR, como CELULAR o MOCHILA), así que llevan posesivo igual que el
  // resto de bienes personales; TAXI/MICRO/TRUFI en cambio son transporte
  // público, no del declarante, y mantienen el artículo indefinido.
  'AUTO': _Lex(_Role.objeto, 'mi auto'),
  'MOTOCICLETA': _Lex(_Role.objeto, 'mi motocicleta'),
  'TAXI': _Lex(_Role.objeto, 'un taxi'),
  'BICICLETA': _Lex(_Role.objeto, 'mi bicicleta'),
  'MENSAJE': _Lex(_Role.objeto, 'un mensaje'),
  'COMPROBANTE': _Lex(_Role.objeto, 'un comprobante'),
  'RESPALDO': _Lex(_Role.objeto, 'un respaldo'),
  'VIDEOLLAMADA': _Lex(_Role.objeto, 'una videollamada'),

  // DESCONOCER es una seña propia para "no conocer" (no NO + CONOCER): su
  // lexema ya trae la negación horneada porque no hay una glosa NO previa
  // de la que derivarla. DENUNCIAR faltaba del todo — "¿desea denunciar?"
  // del corpus penal judicial §4 se perdía entera (corpus §4, auditoría
  // 2026-09).
  'DESCONOCER': _Lex(_Role.verboAccion, 'no conozco a esa persona'),
  'DENUNCIAR': _Lex(_Role.verboAccion, 'quiero presentar una denuncia'),

  // APELLIDO/CARNET/ANOS_EDAD estaban en `_admiteDetalle` (admiten
  // deletreo/dígitos) pero no en el lexicón: sin entrada, `_extractDetails`
  // no las distinguía de una racha de letras y las fundía en el detalle de
  // la glosa anterior ("Mi nombre es Juanapellidoperez.", Fase 1 de
  // identificación, auditoría 2026-09).
  'APELLIDO': _Lex(_Role.marcador, 'mi apellido es'),
  'CARNET': _Lex(_Role.marcador, 'mi carnet de identidad'),
  'ANOS_EDAD': _Lex(_Role.marcador, 'tengo esa edad'),
};

enum _Role {
  sujeto,
  personaDesc,
  rasgo,
  verboAgresion,
  testigo,
  verboAccion,
  objeto,
  documento,
  lugar,
  institucion,
  servicio,
  emocion,
  urgencia,
  tramite,
  motivo,
  tiempo,
  marcador,
  descriptor,
  interrogativa,
}

class _Lex {
  final _Role role;
  final String es;

  const _Lex(this.role, this.es);
}
